README.md

…if you think it's useful. Also interested in any changes/suggestions you might have to the app, where's the best place to chat/email?

Add reference to SVGOMG

---

plugins/_path.js
plugins/mergePaths.js

Hi. Great project, I love it. 
I fixed a very small typo for you that was annoying me. :)

Small spelling typo in mergePaths

---

plugins/removeUselessDefs.js

Don't remove `styles` in removeUselessDefs.js

---

README.md
README.ru.md

I've changed the readme files according to #327, so the users can see exactly which plugin does what, and which to turn on/off.

Changes readmes according to #327

---

plugins/removeAttrs.js

Add description to eliminate ugly `undefined` in `--show-plugins` output

Add description for removeAttrs plugin

---

.svgo.yml
plugins/removeStyleElement.js
test/plugins/removeStyleElement.01.svg

I'm going ahead with recreating. Hopefully this is the right place.

New plugin: Remove style elements - disable by default.

---

plugins/removeUnknownsAndDefaults.js
test/plugins/removeUnknownsAndDefaults.09.svg

Plugin removeUnknownsAndDefaults.
If an element is encountered that doesn't exist in collections.elems, unhandled exception occurs as there is no existence check.
Encountered with this xml block (Illustrator export)
```
<metadata>
<sfw  xmlns="&ns_sfw;">
<slices></slices>
<sliceSourceBounds  height="67.3" width="85.9" y="-40.8" x="-42.5" bottomLeftOrigin="true"></sliceSourceBounds>
</sfw>
</metadata>
```

fix TypeError("Can't get property contents of undefined") 

---

.svgo.yml
package.json
plugins/minifyStyles.js
test/plugins/minifyStyles.01.svg

This PR adds the minifyStyles plugin.
It minifies styles in style elements and style attribute of the elements using CSSO.
CSSO related options can be passed through using the csso option key of that plugin.
With best regards

Add minifyStyles plugin, test and dependencies.

---

docs/how-it-works/en.md

Change sentence structure to make it more readable

Minor English tweak

---

lib/svgo/js2svg.js
lib/svgo/jsAPI.js
plugins/addAttributesToSVGElement.js
test/plugins/addAttributesToSVGElement.01.svg
test/plugins/addAttributesToSVGElement.02.svg

Allows adding valueless attributes to the svg element.

adds addAttributes plugin

---

.svgo.yml

Allows use of the addAttributesToSVGElement by adding to defaults plugins list.

Adds addAttributesToSVGElement to default plugins list.

---

docs/how-it-works/en.md

I tried to test my plugin with the old docs and it was not working so after I had a look into some other plugins I decided to update the docs here a little bit.

updating the docs on the testing section

---

README.md
README.ru.md

Hey! I've created Telegram Bot for SVGO. I think that Telegram is a great platform for infinite number of useful tools. This one is among them.

Add to readme information about svgo_bot

---

.svgo.yml
README.md
README.ru.md
plugins/removeScriptElement.js
test/plugins/removeScriptElement.01.svg

addresses https://github.com/svg/svgo/issues/395

add removeScriptElement plugin

---

plugins/removeUselessDefs.js

I think that's more clear now, .reduce when it does side-effects is a bit nasty

clean .reduce with side-effects

---

plugins/collapseGroups.js
test/plugins/_index.js
test/plugins/collapseGroups.14.svg

I don't use arrow functions, because ugligyJS doesn't like them sadly

remove useless switch groups

---

lib/svgo.js
lib/svgo/config.js

This allows the user to mimic using the `--datauri` flag programatically.

Allow datauri option on js api

---

plugins/cleanupNumericValues.js
test/plugins/cleanupNumericValues.01.svg

@GreLI I did a stupid mistake, sorry, added a test

fix viewBox round

---

plugins/_collections.js
test/plugins/convertColors.03.svg

#757 shorthex false does not transform f00

---

plugins/convertShapeToPath.js
test/plugins/convertShapeToPath.04.svg

The ability to convert circles and ellipses to paths has been requested a few times, for example in #652.
This pull request adds the ability to do just that.
LMK what you think!
See #702 for earlier work on this.

Convert circles/ellipses to paths

---

plugins/inlineStyles.js
test/plugins/inlineStyles.18.svg
test/plugins/inlineStyles.19.svg

Fixes https://github.com/svg/svgo/issues/825.

Fix matchedOnlyOnce cleaning up classes/IDs despite matching more than once

---

README.md

This just adds a link to inkscape-svgo to English README.

inkscape-svgo

---

README.md

Clarify how to enable/disable multiple plugins

---

CHANGELOG.md

Fixed attribution of CSS Color Module 4 fix

---

README.md

I made some minor changes to the README to improve its readability.

Minor edits to the opening paragraph of the README

---

plugins/removeHiddenElems.js

The name of the plugin is misleading as previously it wasn't removing hidden attributes.

Added visibility attribute handling for removeHiddenElems

---

README.md

Add macOS app image shrinker https://image-shrinker.com / https://github.com/stefansl/image-shrinker

Add image shrinker

---

examples/test.js

I noticed a typo in examples :)

fix typo in examples

---

plugins/_collections.js

The Visio SVGExtensions namespace is used to store parameters specific to Visio, so a Visio document can be saved as SVG and reopened without fidelity loss, just like the primary .vsdx format. Since it’s editor-specific and can be pretty large, add it to the list of namespaces to filter out.
<details>
<summary>Expand for example</summary>
Before:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ev="http://www.w3.org/2001/xml-events"
xmlns:v="http://schemas.microsoft.com/visio/2003/SVGExtensions/" width="11.6929in" height="8.26772in"
viewBox="0 0 841.89 595.276" xml:space="preserve" …
```

Add Microsoft Visio XMLNS to removeEditorsNSData

---

plugins/cleanupNumericValues.js

Don’t round `version` attribute

---

lib/svgo.js
test/jsapi/_index.js

feat: offer ES module interop default export (#934)

---

lib/svgo.js

This is useful, when you want to optimize a bunch of files at once.  Thanks to this small change, you can just Promise.all the optimizations, then use the results to overwrite the source files with the optimized content.

Return the path

---

package.json

Also switched the constraint to `^` since js-yaml is very stable

Update js-yaml to version 3.12

---

package.json

One less rc in the dependencies :)

Update css-select to version 2

---

lib/svgo/js2svg.js

Make default config behave as immutable

---

README.md
README.ru.md

I don't speak Russian; the Russian here is from Google Translate and is probably flawed.
Closes #1013

Add prefixIds to readme

---

package-lock.json
package.json

Fixes error described in #1088 
Breaks strict bitbucket pipelines

Bump up js-yaml version to fix DoS vulnerability

---

package-lock.json
package.json

fix for issue #1099
also resolves 2 other npm audit issues

🔧fix: update js-yaml for Code Injection warning

---

README.md

Document multipass option

---

README.md
README.ru.md

I found myself multiple times checking if a plugin is active by default or not. This makes it easier by adding a `Default` column, rather than having the `(disabled by default)` message

[Docs] Add active column in plugins table

---

lib/svgo.js

Title says it all.
Please review.

Change wording of API doc comment

---

README.md
README.ru.md

Updated Readme, added Figma plugin link -https://www.figma.com/c/plugin/782713260363070260/Advanced-SVG-Export

Add Figma plugin link to Readme

---

README.md

Update README with note on glob support on Windows

---

examples/test.js
lib/svgo.js
lib/svgo/coa.js
test/jsapi/_index.js
test/plugins/_index.js
test/svgo/_index.js

Dropped SVGO class and provided "optimize" function with svg and config
as inputs and "createContentItem".

Simplify svgo api

---

.github/workflows/main.yml
.gitignore
lib/svgo/coa.js
lib/svgo/tools.js
package-lock.json
package.json
plugins/prefixIds.js
rollup.config.js
test/browser.js
test/coa/_index.js

The was a lot of requests to provide browser compatible module. In this
diff I added `svgo/dist/svgo.browser.js` bundle and tested it with
playwright.

Provide es module bundle for browser

---

.github/workflows/main.yml

This is so that we get a nice colored output

CI: specify `FORCE_COLOR: 2`

---

.gitignore
package-lock.json
package.json

[c8](https://github.com/bcoe/c8) is quite [more lightweight](https://packagephobia.com/result?p=nyc%2Cc8) and probably faster too.

Switch  to c8 for coverage

---

plugins/convertTransform.js

This should be the last [LGTM](https://lgtm.com/projects/g/svg/svgo/?mode=list) non-cosmetic issue :)

convertTransform: remove unused assignment

---

package-lock.json
package.json
test/svg2js/_index.js
test/svg2js/test.entities.svg
test/svgo/_index.js
test/svgo/entities.svg

Ref https://github.com/svg/sax/releases/tag/v0.1.1
This fixes enother case in [regression tests](https://github.com/svg/svgo/pull/1357).

Fix parsing xml entities

---

README.md
package.json
plugins/_collections.js
plugins/_path.js
plugins/_transforms.js
plugins/cleanupEnableBackground.js
plugins/convertColors.js
plugins/convertEllipseToCircle.js
plugins/convertPathData.js
plugins/convertShapeToPath.js
plugins/convertTransform.js
plugins/removeEmptyContainers.js
plugins/removeEmptyText.js
plugins/removeHiddenElems.js
plugins/removeMetadata.js
plugins/removeStyleElement.js
plugins/removeViewBox.js

I had to remove `http://entropyinteractive.com/2011/04/gjk-algorithm/` since the domain is up for sale.

Use https when possible and remove an inactive domain

---

package-lock.json
package.json
test/browser.js
test/coa/_index.js
test/config/_index.js
test/config/fixtures/module-not-found.js
test/jsapi/_index.js
test/plugins/_index.js
test/svg2js/_index.js
test/svgo/_index.js

Will format the code with prettier in a few commits.

Format tests with prettier

---

lib/css-tools.js
lib/svgo-node.js
lib/svgo.js
lib/svgo/coa.js
lib/svgo/config.js
lib/svgo/css-class-list.js
lib/svgo/css-select-adapter.js
lib/svgo/css-style-declaration.js
lib/svgo/js2svg.js
lib/svgo/jsAPI.js
lib/svgo/plugins.js
lib/svgo/svg2js.js
lib/svgo/tools.js

Format lib with prettier

---

examples/test.js
plugins/_collections.js
plugins/_path.js
plugins/_transforms.js

Format plugins utilities with prettier

---

lib/svgo/css-select-adapter.js
package-lock.json
package.json

This is necessary for better control while implementing new style
manager.

Host css-select adapter

---

plugins/inlineStyles.js
test/plugins/_index.js
test/plugins/inlineStyles.20.svg

This fixes one more case in regression tests.
Also I added support for description in test cases.
This will let make tests more atomic.

Ignore <style> with invalid type attribute

---

.github/workflows/main.yml
lib/css-tools.js
lib/svgo/css-style-declaration.js
lib/svgo/plugins.js
lib/svgo/tools.js
package-lock.json
package.json
tsconfig.json

Added Typescript support via JSDoc comments for some files.
The code has really outdated type signatures, so in order to fully type the codebase the changes need to be incremental.
To check the types run:
`npx tsc`

Add TS support

---

package-lock.json
package.json
rollup.config.js

Closes #1390
**Results:** 826 KB → 551 KB _(–275 KB)_

Remove whitespaces and comments from the browser bundle

---

lib/css-tools.js
lib/style.js
lib/svgo/css-select-adapter.js
lib/svgo/js2svg.js
lib/svgo/svg2js.js
plugins/minifyStyles.js
plugins/prefixIds.js
plugins/removeDesc.js
test/svg2js/_index.js

Ref https://github.com/syntax-tree/xast
More consistent naming and distinction by type looks a bit cleaner.

Convert cdata and text nodes to xast

---

lib/css-tools.js
lib/style.js
lib/svgo/css-select-adapter.js
lib/svgo/js2svg.js
lib/svgo/jsAPI.js
lib/svgo/plugins.js
lib/svgo/svg2js.js
plugins/addAttributesToSVGElement.js
plugins/addClassesToSVGElement.js
plugins/cleanupEnableBackground.js
plugins/cleanupIDs.js
plugins/collapseGroups.js
plugins/inlineStyles.js
plugins/mergePaths.js
plugins/minifyStyles.js
plugins/moveElemsAttrsToGroup.js
plugins/moveGroupAttrsToElems.js
plugins/prefixIds.js
plugins/removeDesc.js
plugins/removeEmptyContainers.js
plugins/removeEmptyText.js
plugins/removeHiddenElems.js
plugins/removeUnknownsAndDefaults.js
plugins/removeUnusedNS.js
plugins/removeUselessDefs.js
plugins/reusePaths.js
plugins/sortDefsChildren.js
test/svg2js/_index.js

Ref https://github.com/syntax-tree/xast
Renamed content to children to match xast spec.

Convert element children to xast

---

plugins/_path.js
plugins/convertPathData.js

Slight code simplification. Each command is processed exclusively
without assumtions. Removed moveto and closepath common coords
reference, handle in applyTransform instead. Rely on new path data
naming.

Refactor convertToRelative

---

lib/svgo/jsAPI.js
plugins/_applyTransforms.js
plugins/cleanupEnableBackground.js
plugins/cleanupIDs.js
plugins/collapseGroups.js
plugins/convertEllipseToCircle.js
plugins/convertShapeToPath.js
plugins/convertStyleToAttrs.js
plugins/convertTransform.js
plugins/inlineStyles.js
plugins/moveElemsAttrsToGroup.js
plugins/moveGroupAttrsToElems.js
plugins/removeAttributesBySelector.js
plugins/removeAttrs.js
plugins/removeDimensions.js
plugins/removeEditorsNSData.js
plugins/removeEmptyAttrs.js
plugins/removeNonInheritableGroupAttrs.js
plugins/removeUnknownsAndDefaults.js
plugins/removeUnusedNS.js
plugins/removeUselessStrokeAndFill.js
plugins/removeViewBox.js
plugins/removeXMLNS.js
plugins/reusePaths.js

delete operator is more explicit and not much harder to use.

Replace removeAttr with delete operator

---

lib/svgo/css-select-adapter.js
lib/svgo/js2svg.js
lib/svgo/jsAPI.js
plugins/_applyTransforms.js
plugins/_path.js
plugins/addAttributesToSVGElement.js
plugins/cleanupIDs.js
plugins/cleanupListOfValues.js
plugins/cleanupNumericValues.js
plugins/convertShapeToPath.js
plugins/convertStyleToAttrs.js
plugins/convertTransform.js
plugins/inlineStyles.js
plugins/mergePaths.js
plugins/minifyStyles.js
plugins/moveElemsAttrsToGroup.js
plugins/prefixIds.js
plugins/removeElementsByAttr.js
plugins/removeEmptyContainers.js
plugins/removeHiddenElems.js
plugins/removeOffCanvasPaths.js
plugins/removeUselessStrokeAndFill.js
plugins/reusePaths.js

Got rid from `.attrs`, `.attr()` and `.addAttr()` usages

Access attributes directly

---

lib/svgo/coa.js

Not sure if this was supposed to do some magic?

Fix invalid radix in cli

---

plugins/addAttributesToSVGElement.js
test/plugins/addAttributesToSVGElement.01.svg
test/plugins/addAttributesToSVGElement.03.svg
test/plugins/addAttributesToSVGElement.04.svg

"full" plugins prevents from possible optimisation. We need to migrate
all plugins to "perItem" type and later implement visitor plugin api to
allow state.

Convert addAttributesToSVGElement to item plugin

---

lib/svgo/jsAPI.js
plugins/_applyTransforms.js
plugins/collapseGroups.js
plugins/convertPathData.js
plugins/convertTransform.js
plugins/moveElemsAttrsToGroup.js
plugins/moveGroupAttrsToElems.js
plugins/removeEmptyContainers.js
plugins/removeEmptyText.js
plugins/removeOffCanvasPaths.js
plugins/removeRasterImages.js
plugins/removeUselessDefs.js

In most cases simple check for null is enough.

Remove hasAttr and hasAttrLocal usages

---

README.md

Small typo in the built-in plugins table. Thank you for your work on this project!

Fix typo in README built-in plugins table

---

README.md

I've added a link to a free API to use SVGO. May be useful for somebody!
For transparency sake; I'm one of the creators of the API.

Add "another way to use SVGO"

---

README.md

Thank you for SVGO!
I built a frontend for it https://github.com/sonnyp/OhMySVG
Fun fact about Oh My SVG; SVGO is compiled to ES modules via rollup and run in [GJS](https://gitlab.gnome.org/GNOME/gjs), a SpiderMonkey runtime.

add Oh My SVG to frontends

---

plugins/cleanupAttrs.js
plugins/convertEllipseToCircle.js
plugins/removeDesc.js
plugins/removeDoctype.js
plugins/removeEmptyText.js
plugins/removeMetadata.js
plugins/removeRasterImages.js
plugins/removeScriptElement.js
plugins/removeStyleElement.js
plugins/removeTitle.js
plugins/removeXMLProcInst.js

- cleanupAttrs
- convertEllipseToCircle
- removeDesc
- removeDoctype
- removeEmptyText
- removeMetadata
- removeRasterImages
- removeScriptElement
- removeStyleElement
- removeTitle
- removeXMLProcInst

Refactor basic plugins with visitor api

---

lib/path.test.js
lib/style.test.js
lib/xast.test.js
package-lock.json
package.json
test/coa/_index.test.js
test/config/_index.test.js
test/jsapi/_index.test.js
test/plugins/_index.test.js
test/svg2js/_index.test.js
test/svgo/_index.test.js
tsconfig.json

Mocha doesn't have a lot of features provided by jest.
There is a great assertion library out of the box along with coverage support.
And the most cool feature is inline snapshots.
Mocha also hides errors which makes debugging a nightmare sometimes.

Migrate to jest

---

plugins/convertShapeToPath.js

This plugin also removes invalid polyline and polygon.
Looks like out of plugin scope.
Note: review with hidden whitespaces.

Refactor convertShapeToPath with visitor api

---

plugins/cleanupListOfValues.js
plugins/cleanupNumericValues.js

Convert cleanupListOfValues and cleanupNumericValues to visitor

---

plugins/addAttributesToSVGElement.js
plugins/addClassesToSVGElement.js
plugins/removeAttributesBySelector.js
plugins/removeAttrs.js
plugins/removeElementsByAttr.js

- addAttributesToSVGElement
- addClassesToSVGElement
- removeAttributesBySelector
- removeAttrs
- removeElementsByAttr

Refactor adhoc plugins with visitor api

---

lib/path.js
lib/style.js
lib/types.ts
lib/xast.js
package-lock.json
package.json
plugins/removeHiddenElems.js
tsconfig.json

Covered removeHiddenElems plugin and big part of our code
- path parser and stringifier
- style manager

Cover removeHiddenElems with types

---

plugins/addClassesToSVGElement.js
plugins/inlineStyles.js
plugins/reusePaths.js
test/plugins/addClassesToSVGElement.03.svg

We are gonna remove everything outside of xast.
Here's dropped class prop.

Drop node.class usages

---

plugins/_path.js
plugins/mergePaths.js
tsconfig.json

- covered mergePaths plugin
- covered big path logic

Cover mergePaths plugin with types

---

plugins/cleanupEnableBackground.js
tsconfig.json

Slightly restructured plugin to do less work in case no filters used.

Refactor cleanupEnableBackground with visitor plugin api

---

lib/svgo/tools.js
plugins/cleanupListOfValues.js
plugins/cleanupNumericValues.js
tsconfig.json

- cleanupNumericValues
- cleanupListOfValues

Cover with types numeric values plugins

---

lib/svgo/jsAPI.js
lib/svgo/tools.js
plugins/sortAttrs.js
test/plugins/sortAttrs.01.svg
test/plugins/sortAttrs.02.svg
test/plugins/sortAttrs.03.svg
test/plugins/sortAttrs.04.svg
tsconfig.json

- covered with tsdoc
- slightly simplified (hope so) logic by avoiding loop over order array
in every compare function call
- rewrote tests

Refactor sortAttrs plugin

---

plugins/removeEmptyContainers.js
tsconfig.json

Refactor removeEmptyContainers

---

README.md

Minor stylistic improvement for concise manual.

In-code comments shorten the commands section

---

plugins/moveGroupAttrsToElems.js
plugins/removeNonInheritableGroupAttrs.js
tsconfig.json

Batched in one PR. Pretty simple changes. Just migrated to api and
added more safety checks for types.

Refactor removeNonInheritableGroupAttrs and moveGroupAttrsToElems

---

plugins/convertStyleToAttrs.js
tsconfig.json

Did not rewrite much, just migrated to tsdoc and visitor plugin api.
This plugin will be obsolete eventually.

Refactor convertStyleToAttrs

---

plugins/removeDimensions.js
plugins/removeXMLNS.js
tsconfig.json

Migrated both to visitor api and tsdoc

Refactor removeDimensions and removeXMLNS

---

CHANGELOG-old.md
README.md

Fix broken link to sponor's logo (Fontello).

README.md: fix broken image link

---

package.json

Just increments the version. We've got quite a few bugs fixed now, so may be worth doing a patch release.

chore: increment patch version

---

README.md

Hi 👋🏿 
The old link was broken, so I updated it^^

chore: update postcss-svgo link

---

package.json
test/regression.js

Change the link of the homepage from this Git repository (which is already documented in `bugs` and `repository` to a link to the documentation.

chore: change link to homepage in package.json

---

test/regression.js

Minor PR that enables a regression test that now passes since the last commit. 🎉

test: enable regression test that now passes

---

package.json

Increment the version to v3.1.0 for the next release.

chore: increment version

---

test/regression.js

Makes two small changes:
* When `NO_DIFF` is set, don't create an empty PNG to populate with diff data.
* Set the viewport in the context instead of each page individually.
Time to run the full SVGO Test Suite proposed in https://github.com/SethFalco/svgo/pull/1.
| Environment | Time |
|---|---|
| GitHub Actions (2 cores) | 20.2 minutes |
| My personal laptop (4 cores, 8 threads) | 14.5 minutes |

ci: dont create diff png if no_diff

---

package.json

Increment the version to v3.2.0. 🎉

chore: increment version to 3.2.0

---

lib/style.js
package.json
yarn.lock

Tracks upstream commit:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9d07a5fc9b325b113dbf18a9b949eab03acf9c89

chore: Upgrade @types/css-tree to remove @ts-ignore comment

---

docs/03-plugins/remove-title.mdx

Noticed here: https://svgo.dev/docs/plugins/remove-title/#:~:text=The%20SVG%20is%20purly%20aesthetic

Fix "purly" typo

---

package.json

Increment version so we can release v3.3.1.

chore: increment version to 3.3.1

---

docs/02-preset-default.mdx
package.json

Makes a few very minor wording revisions in the package.json and documentation.

chore: minor wording in package.json and docs

---

README.md

Updated recursive usage example

---

lib/svgo.d.ts

chore: export the `Output` type

---

lib/svgo.d.ts

This PR adds export type `CustomPlugin` and `PluginConfig`.
Which makes it easier to secondary development.

feat: export type `CustomPlugin` and `PluginConfig`

---

docs/04-plugins/convertTransform.mdx

repair broken link reported in #2092

docs: fix dead link in convertTransform.mdx (#2092)

---

docs/06-migrations/01-migration-from-v3-to-v4.mdx

A very minor rewording of the migration guide to make it more comfortable to read.

docs: minor revision to wording of migration

---

lib/version.js
package.json

I plan to do the stable release for SVGO v4 today! 💪(•ᴗ•💪)

chore: prepare v4 stable release
