lib/svgo/jsAPI.js
I made `parentNode` enumerable again, breaking `JSON.stringify(node)`. If being able to convert a node to JSON is useful, a custom `.toJSON` would fix that, but as far as I can tell it was only used for cloning.
=> JSAPI.prototype.clone - fixes #311

lib/svgo/config.js, test/config/_index.js
When experimenting with a new plugin, or just doing custom things in my app, it's a pain to have to fork SVGO and add a plugin there then keep the fork up to date. It would be great to just be able to pass a custom plugin into the plugins list.
This pull request adds that functionality, so you can do something like:
```javascript
new SVGO({
plugins: [
myCustomPugin: {
type: ‘perItem’,
fn:   function(item) {
/* do stuff */
}
}
]
});
```
=> Allow providing custom plugins

README.md
When using the node.js config, having removeMetaData instead of removeMetadata will crash (can't find the plugin)
=> Fixed removeMetadata in the doc

README.md
Noticed a typo in the readme when trying to use the convertStyleToAttrs plugin.
=> Fix plugin name typo in README.md.

lib/svgo/js2svg.js
Allow config to specify `useShortTags` (default true).
When `useShortTags` is true, empty elements are terminated with />
When `useShortTags` is false, empty elements are closed with a full closing tag
e.g. < / path >
=> Allow config to specify use of self closing tags

lib/svgo/coa.js
I trust that svgo works, and the output of my build process is overly long as it is. Add a `-q` / `--quiet` option to suppress all the chatter and only show important / error messages.
=> Add option --quiet

lib/svgo/tools.js
Handle data URI scheme containing optional charset field like `data:image/svg+xml;charset=US-ASCII,%3C%3Fxml%20...` .
=> Add charset handling on Data URI

lib/svgo.js
It's good practice to declare the file type being required. This will help svgo play nice with JSPM. Additionally, one of the requires was already declaring its file type. So, this PR adds consistency, too.
=> Use explicit file types

lib/svgo/coa.js, lib/svgo/js2svg.js, test/mocha.opts, test/svgo/_index.js, test/svgo/test.svg
I took a stab at adding an option to indent svgs for #465 
```bash
svgo --pretty --indent 2 image.svg
```
```js
new svgo({ 
full: true, 
plugins: [], 
js2svg : { 
pretty: true,
indent: 2 
}
}).optimize(file, function(out) { ... });
```
It defaults to 4 to stick with the existing convention, but hopefully provides a little more flexibility to those who are looking to have different indention settings.
=> Add option to indent when pretty printing svg

plugins/convertColors.js, test/plugins/convertColors.04.svg
This is related to #497, but instead of creating a new plugin it adds an additional param to the existing `convertColors` plugin. 
Part of the issue that this addresses, if a color is defined within an SVG you can't override the color easily in CSS without manually editing the SVG. With this new param, you can automatically convert colors to `currentColor` allowing CSS overrides.
The only downside of it being a param within `convertColors`, is that it will override any other params when set to true. That's why initially `currentColor` defaults to `false`.
The only other potential change I could see is to take into account `transparent` values. I'm not sure if transparent values should or should not be converted. For my use case, if a color value is transparent we don't need it changed, …
=> Add currentColor param to convertColors plugin

plugins/moveGroupAttrsToElems.js
I'm writing a plugin that, among other things, makes changes to transform values. I've found that my plugin throws an error when used with `moveGroupAttrsToElems`.
moveGroupAttrsToElems is correctly copying transforms from a group to each child element, but it's assigning the "new" attribute to the element by referencing the original instead of creating a new copy of it. This results in my plugin making changes to the same referenced transform for each element.
This PR ensures a new version of the attribute is created, fixing the issue.
=> moveGroupAttrsToElems: new transform attribute shouldn't be a reference

plugins/cleanupIDs.js
when running cleanupIds with minify:false option it does not save a reference to all ids and removes ids that shouldn't be removed.
This fix adds a var that keeps a ref to the original id even if minify is not defined
=> When minify:false cleanupIds deletes too many ids

plugins/sortAttrs.js, test/plugins/sortAttrs.01.svg
This fixes some annoyances with sortAttrs:
- Attributes such as `stroke-linejoin` were not included with `stroke-width`, `stroke-miterlimit` etc.. Now all attributes that begin with `stroke-` are sorted alphabetically immediately after `stroke`. Same for fill and marker attributes.
- Prefixed attributes are moved to the end of the list, except `xmlns`, which is still at the start.
- Any attributes not listed in the order are sorted alphabetically.
=> Improve sortAttrs plugin

plugins/addClassesToSVGElement.js
If you run `svgo` repeatedly over a set of files it will continue to add the same class over and over:
```yaml
plugins:
- addClassesToSVGElement:
className: icon
```
```svg
<svg class="icon icon icon icon icon">...
```
This commit changes `addClassesToSVGElement` to only add classes that are not already present.
=> addClassesToSVGElement: avoid repeating classnames

.svgo.yml, plugins/removeXMLNS.js
Previously seen in #409.
This is useful for cases where you are inlining `<svg>` elements - [HTML5 does not support namespaces](https://www.w3.org/TR/html5/syntax.html#foreign-elements).
=> add removeXMLNS plugin

plugins/convertColors.js
In addition to the current behavior, the following options were added:
1) Set a color that should be replaced to `currentColor`, for example `convertColors: { currentColor: '#030303' }`, so all fills and strokes with `#030303` color value will be replaced to `currentColor`.
2) Set a color(s) to be replaced using a regexp, for example `convertColors: { currentColor: /#FF.{4}/ }`, so all colors with the red value of `FF` will be replaced to `currentColor`.
=> More options for setting "currentColor"

README.md, lib/svgo/coa.js
Add the missed possibility to pass a `JSON` string to `--config` argument
solves #636
=> Update CLI help

plugins/cleanupIDs.js, test/plugins/cleanupIDs.06.svg, test/plugins/cleanupIDs.07.svg, test/plugins/cleanupIDs.08.svg, test/plugins/cleanupIDs.09.svg, test/plugins/cleanupIDs.10.svg
When processing svg files that make use of [svg-stacks](http://xn--dahlstrm-t4a.net/svg/structure/svgstack-usage.html) or [view elements](https://betravis.github.io/icon-methods/svg-sprite-sheets#with-a-custom-view) cleanupIDs plugin would either leave the file untouched (when `<style>` is present) or delete all ids from `<view>` elements.
I have added **force** (false by default) parameter to **cleanupIDs** config that allows to ignore the presence of `<style>` and `<script>` and clean up anyway. In case of **force = true** the onus would be on the user not to reference elements by id in those tags. Or to include ids not to be cleaned in **except** parameter.
**except**, which can be a single id or an Array of ids, allows to keep user-specified ids from being removed or minified. This …
=> Allow to force clean svg with style or script, excepting custom ids (in cleanupIDs)

lib/svgo/coa.js
Resolves #690 
Added `--recursive/-r` flag to process folders recursively.
Usage: `svgo -f ./my-folder -r`
Just before checking if the "file" is an SVG, check if it's actually a directory and call `optimizeFolder()` on that directory.
Let me know if you require any further adjustments. I wanted to keep them as light as possible.
=> Resolves #690: Add option to process folders recursively.

plugins/removeUnknownsAndDefaults.js, test/plugins/removeUnknownsAndDefaults.11.svg, test/plugins/removeUnknownsAndDefaults.12.svg
Closes #684.
Adds a `keepAriaAttrs` option to `removeUnknownsAndDefaults`, with a default value of `true`. And adds two cases to make sure it works.
=> Add keepAriaAttrs to removeUnknownsAndDefaults

lib/svgo/config.js
Introduced in #735, change `defaults.config` assignation to `defaults.datauri`; otherwise, property is not read.
=> config: fix datauri config object name

package.json
While `css-tree` is in alpha stage its version must be pinned, because with any new version API and AST format can change, and lead to issues with wrong version installation (see #813).
It may be relaxed when `css-tree` will out of alpha stage in the nearest future.
=> Pin css-tree version (fixes #813)

plugins/addAttributesToSVGElement.js, test/plugins/addAttributesToSVGElement.03.svg
Currently this plugin only supports attribute names. This PR adds the functionality for attribute values.
=> Updated addElementsToSVGElement plugin to support attribute values

lib/svgo/coa.js
1.0.x seems to have introduced some extra junk in the output if you use `svgo` in `stdout` mode (i.e. `-o -`). Using the "with STDIN / STDOUT" usage documented in the [README](https://github.com/svg/svgo/blob/master/README.md) as an example:
```
$ cat examples/test.svg | bin/svgo -i - -o - > test.min.svg
$ cat test.min.svg 
<svg width="10" height="20">test</svg> 
Done in 10 ms!
0.058 KiB - 35.6% = 0.037 KiB
```
Obviously that extra stuff doesn't belong in `test.min.svg`.
This worked correctly in v0.7.x, I *believe* because the [codepaths were more separated and process.stdout.write() was used instead of console.log()](https://github.com/svg/svgo/blob/v0.7.2/lib/svgo/coa.js#L312).
Two proposed changes here:
- don't call `printTimeInfo()`/`printProfitInfo()` unless `output != '-'`
- …
=> Fixes for svgo's stdout mode in 1.0.x

examples/test.js
There is (understandably) some confusion about how the config files works (see https://github.com/svg/svgo/issues/439) so I've added an example (the one given in that issue) in place of a fairly useless placeholder
=> Added config example to node example file

plugins/prefixIds.js, test/plugins/prefixIds.05.svg
When using the prefixIDs plugin  on an SVG with multiple linear gradients, url() values are not replaced correctly because we use `exec` to capture values using the regex. Exec preserves the last matched index, which is undesirable in this case.
Please ref this [ stackoverflow answer ](https://stackoverflow.com/questions/4724701/regexp-exec-returns-null-sporadically) for more information about this.
=> Fix issue with prefixIDs plugin not replacing url() refs correctly

plugins/collapseGroups.js, test/plugins/collapseGroups.15.svg
When the inner element has the `inherit` value, overwrite with the value from the parent `<g>` element.
=> Fixes #915 for collapseGroups

.gitignore, plugins/prefixIds.js
i use it like this:
```
plugins: [
{convertPathData: false},
{prefixIds: {
prefix: node => {
const elementName = node && node.elem
if(!elementName || elementName === 'svg' || elementName === 'use'){
return false
}
return 'some-prefix'
}
}}
]
```
and i expect no prefix when i return prefix as false.
it can also be used as
```
plugins: [
{convertPathData: false},
{prefixIds: {prefix: false}}
]
```
=> Prefix ids plugin don't add prefix if prefix is false

examples/test.js
Update test.js (which incorrectly references nonexistent transformsWithOnePath plugin)
=> fix for references nonexistent transformsWithOnePath plugin

plugins/sortAttrs.js, test/plugins/sortAttrs.02.svg
i wanted this option so that `xmlns` attributes weren't always at the front of the node.
=> [plugin] sortAttrs: add xmlns order option

lib/svgo/css-class-list.js, lib/svgo/css-style-declaration.js, lib/svgo/jsAPI.js, test/svg2js/_index.js, test/svg2js/test.svg
Since the introduction of the inlineStyles plugin, the jsAPI clone method no longer works (`JSON.parse(JSON.stringify(...)` throws an error due to the circular references).
This pull request fixes this by introducing two new `clone()` methods for the `CSSStyleDeclaration` and `CSSClassList` classes.
=> fix broken jsapi clone method

plugins/_path.js, test/plugins/convertPathData.19.svg
Fixes #856.
Ideally we would also remove the `vector-effect` attribute from the `<path>` after applying the transformation... but I don't think we can do this because there could be a parent transform that is also transforming the path. 
If you have any ideas on how we could remove the `vector-effect` attribute (maybe in another plugin?), let me know.
=> dont transform stroke width for non-scaling-strokes

plugins/convertPathData.js
Added parameter forceAbsolutePath to get absolute SVG path (even when the relative path is shorter).
This is useful for generating mobile assets, android vector drawables etc.
=> Allow to forceAbsolutePath output for convertPathData plugin.

plugins/removeUnknownsAndDefaults.js, test/plugins/removeUnknownsAndDefaults.13.svg, test/plugins/removeUnknownsAndDefaults.14.svg
Fixes https://github.com/svg/svgo/issues/787
Allows for the option to keep `role` attributes by setting `keepRoleAttr: true` within `removeUnknownsAndDefaults`.
This attribute is used for accessibility reasons and should be kept under some (but not all) circumstances.
=> Adds keepRoleAttr option for removeUnknownsAndDefaults

package.json
This enables 'npm i && npm run lint' to work with no globals required
=> adds jshint to devDependencies

.svgo.yml, README.md, plugins/removeAttributesBySelector.js, test/plugins/removeAttributesBySelector.01.svg, test/plugins/removeAttributesBySelector.02.svg, test/plugins/removeAttributesBySelector.03.svg
This pull request adds the `removeAttributesBySelector` plugin. Allowing the removal of attributes in elements found by a css selector.
For a project I'm currently working on, I need to remove the attribute `fill` only if it has the value `#00ff00`. The `removeAttrs` plugin only queries the element name and is not able to meet this need.
I'm happy to add other plugins like `addAttributesBySelector`, or refactor `removeAttrs`, or create another plugin that combines all this functionality. For now, I've just left it as a separate plugin.
```
plugins:
- removeAttributesBySelector:
selector: "[fill='#00ff00']"
attributes: "fill"
<rect x="0" y="0" width="100" height="100" fill="#00ff00" />
↓
<rect x="0" y="0" width="100" height="100"/>
```
=> Add removeAttributesBySelector plugin

.svgo.yml, plugins/removeOffCanvasPaths.js, test/plugins/removeOffCanvasPaths.01.svg, test/plugins/removeOffCanvasPaths.02.svg, test/plugins/removeOffCanvasPaths.03.svg, test/plugins/removeOffCanvasPaths.04.svg, test/plugins/removeOffCanvasPaths.05.svg
The plugin is rudimentary: it compares each `<path>` to the viewBox using `intersects()` and removes those that don't. The plugin is disabled by default.
=> Add removeOffCanvasPaths plugin

plugins/removeAttrs.js, test/plugins/removeAttrs.03.svg
Hello, I just coded this up as a follow up for the issue I just logged https://github.com/svg/svgo/issues/999 .. I've added some explanations in my diff to hopefully make it easy to review.
Also, nothing output when I ran: `npm run lint` and `npm test` returns `  307 passing (1s)`. Let me know if you like this and/or if there's any conventions I missed. Thanks for your time!
=> Add the preserveCurrentColor option to the removeAttrs plugin.

plugins/cleanupIDs.js, test/plugins/cleanupIDs.12.svg, test/plugins/cleanupIDs.13.svg, test/plugins/cleanupIDs.14.svg, test/plugins/cleanupIDs.15.svg
There is currently an option to opt out of the ID cleanup by specifying IDs that we want left alone. This would also be useful to do on prefixes. That way, we could say, preserve `rect_*`, without having to enumerate all the possibilities of `*`. And, having both prefix and full string matching is useful, so you ca, for example, preserve `rect` specifically but not `rect_blue`.
This change adds another config array that takes in a list of prefix strings, and preserves any IDs that start with one of those prefixes. Also adds tests for this behaviour standalone, and in conjunction with `force` and the full-string ID preserving config.
PTAL @GreLI
=> Add config to preserve IDs based on prefix matching

plugins/mergePaths.js
This request addresses the feature enhancement requested in #800. It allows a `force` option be passed to the `mergePaths` plugin, forcing it to combine all `<path>` attributes into a single one. The option is disabled by default.
=> (Fix #800) Add option to the mergePaths plugin, forcing all path attributes to be combined

README.md, plugins/removeDimensions.js, test/plugins/removeDimensions.04.svg, test/plugins/removeDimensions.05.svg
This change allows removeDimensions on SVG's that lack the viewBox attribute but has valid width and height attributes.
I have such SVG's in my project and I prefer to not edit them by hand.
This change is backwards compatible, I did not change any of the previous unit tests, but added two additional ones for the new functionality.
=> Make removeDimensions add viewBox if it's missing

plugins/convertEllipseToCircle.js, test/plugins/convertEllipseToCircle.01.svg
This converts non-eccentric ellipse elements to circle elements.
Adobe Illustrator seems to be fond of using ellipses even if their rx === ry.
=> Add ellipseToCircle plugin

plugins/prefixIds.js, test/plugins/prefixIds.07.svg, test/plugins/prefixIds.08.svg, test/plugins/prefixIds.09.svg
This PR adds options for selectively prefixing IDs and/or class names by prefixIds plugin.
See https://github.com/svg/svgo/issues/1062
=> Selectively prefixing IDs and/or class names by prefixIds plugin

lib/svgo.js
This change could be convenience which allows developers to use `config()`.
In my case, I want to initialize config object using `config()` in [vscode SVGO plugin](https://github.com/1000ch/vscode-svgo). I can import it by calling `require('svgo/lib/svgo/config');`, but it's not a provided way and we have to set `noImplicitAny: true` to use in TypeScript project. If this is merged, I'll make a pull request to update type definition in DefinitelyTyped.
=> Export config function to enable to use

lib/svgo/config.js
Fix for issue https://github.com/svg/svgo/issues/1026
`plugin.params` is referenced when plug-in is initialised by name, which causes any modification to parameters affect all images when parsing multiple images.
=> Copy plugin params when initializing plugin by name

package-lock.json, package.json, test/plugins/minifyStyles.10.svg
This PR adds a test for reproducing the `csso` error in and 
fixes https://github.com/svg/svgo/issues/1097 by updating to [latest `csso` `4.0.2`](https://github.com/svg/svgo/issues/1097#issuecomment-547193439).
=> Update csso to 4.0.2 (+semicola in styles test)

lib/svgo.js, plugins/prefixIds.js
This PR adds `multipassCount` to the `info` object that is passed to the plugins.
This allows plugins to know whether they already processed a SVG node/document and how many times. This is necessary for the `prefixIds` plugin to skip in subsequent passes when multipass is used to prevent unintended, multiple prefixing (see https://github.com/svg/svgo/issues/1148).
The `info` object is perfectly suited for this kind of extra/runtime information for the plugins, 
and it is already used by `prefixIds` plugin for obtaining the path of the SVG (node) it is processing.
=> Add multipassCount to info object; skip subsequent passes in prefixIds plugin

plugins/cleanupIDs.js, test/plugins/cleanupIDs.16.svg, test/plugins/cleanupIDs.17.svg, test/plugins/cleanupIDs.18.svg
Prevent 'cleanupIDs' plugin from producing a preserved ID, including one
which matches a preserved prefix, when minifying.
Closes #1158
=> Fix 'cleanupIDs' minify bug due to preserved IDs

lib/svgo.js
As per PR #1173, and commit https://github.com/svg/svgo/commit/71c7fe74b9a6cbbbe6d8e4f318a0d6fb35c1d727, passing `info` to the `SVGO.optimize` function is no longer optional. Without setting `info`, the following error is thrown:
`Cannot set property 'multipassCount' of undefined`
I'm not entirely sure if this was ever meant to be optional, but, it's worked that way up until 1.3.0, and you can find hundreds of examples on GitHub of people using it this way: https://github.com/search?l=JavaScript&q=%22svgo.optimize%22&type=Code
This PR simply sets `info` to an empty object if it's not set, which enables backwards compatibility with 1.3.0 and other versions, which will save people who use "compatible with" versions in their package.json declarations. If you have a better suggestion for how …
=> Default `info` on SVGO.optimize API

plugins/convertPathData.js
This fixes #1166. In the example reported in that bug, `data` was updated at line 460, but writing back to `item.data` doesn't happen until later, which is why line 517 ended up using outdated data.
=> Fix collapsing of repeated commands in convertPathData plugin

.travis.yml, lib/svgo/coa.js, package-lock.json, package.json
Ref https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_mkdir_path_options_callback
Node 10 add "recursive" flag support to fs.mkdir which behaves similar
to mkdirp package.
Though this requires to bump node support.
=> Replace mkdirp with fs.mkdir with recursive flag

lib/svgo/coa.js, package-lock.json, package.json
Node 10 add support for promisified fs methods.
https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api
In this diff I replaced util.promisify package with the new methods.
Though this requires to bump end-of-life node versions.
=> Replace util.promisify with fs.promises

bin/svgo, lib/svgo/coa.js, package-lock.json, package.json, test/coa/_index.js
Ref https://packagephobia.com/result?p=coa https://packagephobia.com/result?p=commander
Coa was not updated for 2 years already and has outdated dependencies.
In this diff I replaced it with commander which has simpler syntax, none
dependencies and require arguments out of the box. Also array argument
is set syntactically which means more user-friendly "help".
=> Replace coa with commander

examples/test.js, lib/svgo.js, lib/svgo/coa.js, lib/svgo/svg2js.js, package.json, test/plugins/_index.js, test/svg2js/_index.js, test/svgo/_index.js
Ref https://github.com/svg/svgo/issues/1015
Looks like `sax` is synchronous and we do not need to listen "end"
event. This allows to avoid all callbacks and make `optimize` method
synchronous.
cc @gregberge @deepsweet
=> Make optimize synchronous

lib/svgo/config.js, test/config/_index.js, test/plugins/_index.js
- replaced named plugin object with "name" field
- dropped support for params in plugin object; use only params to pass plugin options
- dropped support for "boolean plugins"; use active field instead
```diff
-{
-  pluginName: {
-    fn,
-    params: {},
-    ...params
-  }
-}
+{
+  name: 'pluginName',
+  fn,
+  params: {}
+}
```
=> Simplify plugins configuration

lib/svgo-node.js, lib/svgo.js, lib/svgo/coa.js, package-lock.json, package.json, test/coa/_index.js, test/config/_index.js, test/config/fixtures/invalid-array.js, test/config/fixtures/invalid-null.js, test/config/fixtures/invalid-string.js, test/config/fixtures/one/two/config.js, test/config/fixtures/svgo.config.js
Ref https://github.com/svg/svgo/issues/1327
Config file now can only be js. `svgo.config.js` is searched by default.
Otherwise any js module specified in `--config` cli flag.
Config loader is exposed in entry point as `loadConfig(configFile, cwd)`.
=> Implement loadConfig utility

README.md
I added (my) GitHub Action to run SVGO as a [GitHub Action](https://github.com/features/actions) to the README. Thought it might be useful to some.
I suppose the Russian REAMDE should also be updated, but I don't speak Russian so I didn't update it (I allowed edits from maintainters, so feel free to add it :slightly_smiling_face:)
If this is unwanted, feel free to close it. If the position of the item in the list is inappropriate, let me know and I'm happy to update it.
=> Add the SVGO Action as an other way to use SVGO

lib/svgo/coa.js
BTW, `eslint` could prevent this type of mistake.
=> Fix 'ReferenceError: indent is not defined'

lib/svgo.js, test/svgo/_index.js, test/svgo/multipass-prefix-ids.svg, test/svgo/multipass.svg
Ref https://github.com/svg/svgo/issues/1330 https://github.com/svg/svgo/issues/1148 https://github.com/svg/svgo/issues/1133 https://github.com/svg/svgo/pull/1227 https://github.com/svg/svgo/issues/985 https://github.com/svg/svgo/issues/943
Took tests from https://github.com/svg/svgo/pull/1177
cc @strarsis
=> Fix multipass

plugins/convertStyleToAttrs.js
Was flagged by [lgtm](https://lgtm.com/projects/g/svg/svgo?mode=list)
=> convertStyleToAttrs: fix wrong character class

lib/svgo/tools.js
Node.js 10.x which is the minimum supported version supports `Buffer.from`
=> Fix `new Buffer` usage

README.md
Clarified configuration format, simplified CLI example, described
programming api.
=> Add better docs

plugins/reusePaths.js, test/plugins/reusePaths.03.svg
Fixes #1186
By checking whether there are any defs before making an element, it doesn't create an empty `<defs/>` element.
=> fix excessive defs tag

test/coa/_index.js
`.` means any character but we want to match the literal `.`
=> test/coa/_index.js: Fix regex

plugins/convertStyleToAttrs.js, test/svgo/_index.js, test/svgo/style-specifity.svg
Ref https://github.com/svg/svgo/issues/1362 https://github.com/svg/svgo/issues/1360
From the [spec](https://www.w3.org/TR/SVG11/styling.html#UsingPresentationAttributes):
> Presentation attributes have lower priority than other CSS style rules specified in author style sheets or ‘style’ attributes.
Though we replace inline styles with attributes without checking if
thare is any `<style>` element. This makes the plugin unsafe and it
should not be enabled by default.
cc @sk- @strarsis
=> Disable convertStyleToAttrs plugin by default

README.md
NPM install script is missing the `install` keyword.
=> Fix npm install script typo

lib/svgo/js2svg.js, lib/svgo/svg2js.js, plugins/_collections.js, test/plugins/cleanupIDs.09.svg, test/plugins/cleanupIDs.10.svg, test/plugins/cleanupIDs.13.svg, test/plugins/cleanupIDs.14.svg, test/plugins/collapseGroups.13.svg, test/plugins/inlineStyles.13.svg, test/plugins/inlineStyles.16.svg, test/svg2js/_index.js, test/svg2js/test.svg
SVGO configures its SAX parser to normalize whitespace, [collapsing multiple space characters into one](https://github.com/isaacs/sax-js/blob/5aee2163d55cff24b817bbf550bac44841f9df45/lib/sax.js#L640). 
This can change the semantic meaning of SVG content:
- In `<text>` and `<tspan>` nodes when whitespace is being preserved (e.g. `xml:space="preserve"` or `style="white-space: pre"`).
- In `<text>` and `<tspan>` nodes where [glyphs are spaced explicitly using multiple `x` values](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x#tspan). Changing the number of characters in the node changes the indexes of characters (see https://github.com/svg/svgo/issues/1044).
This patch disables space normalization in `sax`. It removes trimming for node names classified as "textContent" in …
=> Preserve whitespace in elements containing text

lib/path.js, lib/path.test.js, package.json, plugins/_path.js
Regexps are quite leaky for complex parsing. Regression tests caught
a few issues related to path parser.
In this diff I implemented the new spec-compliant parser which solves
2 regression cases and covers many edge cases.
=> Implement new path parser

examples/test.js
Old example didn't work with `removeAttrs` plugin. This worked for me and also validated here:
https://github.com/svg/svgo/issues/1344
=> Update example for removeAttrs

lib/style.js, lib/style.test.js, plugins/removeHiddenElems.js, test/plugins/removeHiddenElems.01.svg, test/plugins/removeHiddenElems.02.svg, test/plugins/removeHiddenElems.12.svg
Ref https://github.com/svg/svgo/issues/777
Currently a lot of optimisations are attributes specific and may be
broken because of inline or shared styles.
In this diff I'm trying to solve the problem with getComputedStyle
analog.
`computeStyle` collects attributes, shared css rules, inline styles
and inherited styles and checks whether they can be statically optimised
or left as deoptimisation.
As an example I integrated computeStyle into `removeHiddenElems` plugin
which is fixed bugs with styles in style rules and inline styles.
=> Implement style computing

.github/workflows/main.yml, .gitignore, package-lock.json, package.json, test/regression.js
Visual regressions tests will give us more confidence in SVGO stability.
Test cases are downloaded from w3.org, screenshooted with playwright and
compared with pixelmatch.
See test suite https://www.w3.org/Graphics/SVG/Test/20110816/
Bugs detected with these tests:
- https://github.com/svg/svgo/commit/9b97e06ef69b7961f342c9ee8468c552c9b503a3
- https://github.com/svg/svgo/pull/1371
- https://github.com/svg/svgo/commit/c1d5f0f7a93a6f1c947baa5860ddd40f8d1bb701
- https://github.com/svg/svgo/commit/9de471a0f4bea20581034c2d74b0652c27e0fad0
- https://github.com/svg/svgo/commit/091172a392f6d751855477d51e5c8bd3e44fde97
- https://github.com/svg/svgo/commit/36391564f2d0b2c7ad86c746bacdd6de030ebd3d
- https://github.com/svg/svgo/commit/d14315b68fc1fcb43212219a0da5857ad7a23cd0
- …
=> Test regressions with W3C SVG 1.1 Test Suite

lib/svgo/jsAPI.js, lib/svgo/svg2js.js, lib/svgo/tools.js, plugins/_path.js, plugins/addAttributesToSVGElement.js, plugins/cleanupIDs.js, plugins/convertEllipseToCircle.js, plugins/convertShapeToPath.js, plugins/convertStyleToAttrs.js, plugins/moveElemsAttrsToGroup.js, plugins/moveGroupAttrsToElems.js, plugins/removeDimensions.js, plugins/removeEditorsNSData.js, plugins/removeOffCanvasPaths.js, plugins/removeUnknownsAndDefaults.js, plugins/removeUnusedNS.js, plugins/removeUselessStrokeAndFill.js, plugins/reusePaths.js, plugins/sortAttrs.js, test/jsapi/_index.js, test/svg2js/_index.js
These parts of element and attribute name are easy to extract.
Now we can easily replace attrs with xast attributes object.
=> Remove prefix/local support in elements and attributes

lib/svgo/js2svg.js, lib/svgo/svg2js.js, plugins/removeComments.js, plugins/removeDoctype.js, plugins/removeXMLProcInst.js, test/svg2js/_index.js
Here we add [xast](https://github.com/syntax-tree/xast) support
to three basic nodes: doctype, instruction and comment
Some tests are rewritten instead of checking each field to `.include`
assertion which is able to match shape of object.
=> Convert to xast doctype, instruction and comment nodes

lib/style.js, lib/svgo/css-class-list.js, lib/svgo/css-style-declaration.js, lib/svgo/svg2js.js, plugins/moveElemsAttrsToGroup.js, test/svg2js/_index.js
There is a lot of attributes manipulation which is hard to remove at
once. In this diff I added `attributes` object and wrapped it as proxy
for `attrs` field.
=> Convert attributes to xast with proxy fallback

lib/svgo/jsAPI.js, plugins/_applyTransforms.js, plugins/cleanupAttrs.js, plugins/cleanupIDs.js, plugins/cleanupNumericValues.js, plugins/collapseGroups.js, plugins/convertColors.js, plugins/moveGroupAttrsToElems.js, plugins/removeAttrs.js, plugins/removeEditorsNSData.js, plugins/removeEmptyAttrs.js, plugins/removeNonInheritableGroupAttrs.js, plugins/removeUnknownsAndDefaults.js, plugins/removeUnusedNS.js, plugins/removeUselessStrokeAndFill.js, plugins/sortAttrs.js
These iterators allows to directly manipulate passed value
which does not let us to get rid from legacy "attrs" field.
Object.entries makes it easier to get an access to both attribute
name and value.
=> Replace attributes iterators with for/of

lib/style.test.js, lib/xast.js, plugins/cleanupEnableBackground.js, plugins/cleanupIDs.js, plugins/inlineStyles.js, plugins/minifyStyles.js, plugins/removeHiddenElems.js, plugins/removeUnusedNS.js, plugins/removeViewBox.js, plugins/reusePaths.js
Replaced JSAPI methods with new utilities
- querySelectorAll(node, selector)
- querySelector(node, selector)
- matches(node, selector)
- closestByName(node, elementName)
- traverse(node, fn)
New traverse replaced many in-place implementations (bananas).
=> Migrate ast traversing into xast module

lib/svgo/tools.js
Make the intention clearer than having to look at the ASCI codes. Performance should be the same.
=> Use charAt instead of charCodeAt when possible

package.json, test/config/fixtures/invalid/svgo.config.js
Otherwise, all files are included
=> Specify --ignore-path for ESLint

lib/svgo/css-class-list.js, lib/svgo/css-style-declaration.js, lib/svgo/jsAPI.js, lib/svgo/svg2js.js
https://github.com/svg/svgo/pull/1279 faced some problems with node cloning.
In this diff I moved class/style live objects to JSAPI and made it non
enumerable to avoid deep cloning issues.
class list and style declaration classes are not longer need own clone
methods.
cc @strarsis 
Reparsing is not a big deal since this operation is quite rare. And we achieve here less code and more correctness.
Closes https://github.com/svg/svgo/pull/1449
=> Implement simple node clone

lib/svgo/plugins.js, lib/xast.js, lib/xast.test.js, plugins/mergeStyles.js, test/plugins/mergeStyles.11.svg, tsconfig.json
Visitor is a simple pattern which helps to avoid many type checks
and provide both "perItem" and "perItemReverse" functionality without
fragmentation.
The most important case is an ability to define state which in many
plugins specified either on module level or by polluting `params`.
In this diff I added visit and detachFromParent utilities and refactored
new mergeStyles plugin with it.
Also fixed bug when cdata content is merged into "text" node which is
not always valid.
cc @strarsis @XhmikosR @sk-
=> Add "visitor" plugins support

lib/svgo/coa.js
Hello, 
I ran accross #1392 because we have almost exactly the same issue
We currently have a kinda big custom script allowing us to do filtering on recursive svgo processing and we were trying to migrate to the cli but this feature is missing
So I implementend a tiny option which accept an array of regex pattern that we can use to filter out file descriptors
=> Implement exclude pattern cli option

README.md
Hello !
The PR #1365 disabled `convertStyleToAttrs` plugin by default. However, it's still marked as `enabled` in the README.
Simply fixes that by marking it as `disabled` !
=> Mark convertStyleToAttrs as `disabled` in README

package-lock.json, package.json
Resolves #1488
This updates [the `css-select` dependency](https://github.com/svg/svgo/blob/59876d894ba758814a224cffe26566104018130d/package.json#L98) from `^3.1.2` to `^4.1.2` in order to get [the transitive dependency `css-what`](https://github.com/svg/svgo/blob/59876d894ba758814a224cffe26566104018130d/package-lock.json#L627-L631) updated to `5.0.1`, which [was vulnerable to ReDoS up-to-and-including `5.0.0`](https://app.snyk.io/vuln/SNYK-JS-CSSWHAT-1298035). Given my understanding of SVGO, this means SVGO may be vulnerable as well when provided with a carefully crafted SVG containing CSS.
Alternatively, `css-select` can be set to as low as `^4.0.0` in order to get `css-what` updated to an appropriate version. I just set it to `^4.1.2` as that is the latest version as of opening this …
=> Upgrade css-select from `^3.1.2` to `^4.1.3`

bin/svgo, lib/svgo/coa.js, package-lock.json, package.json
Replace chalk with colorette to remove 5 deps from production installl:
`ansi-styles`, `supports-color`, `color-convert`, `has-flag`, `color-name`.
Also reduce deps when using PostCSS and SVGO together, since PostCSS
uses colorette.
Tested with `yarn install svgo`.
=> Replace chalk with colorette

README.md
I have been working on an open source browser extension called [SVG Gobbler](https://github.com/rossmoody/svg-gobbler) for a few years. Lately the project has utilized SVGO much more directly and predominantly. The eventual plan is to assume all the functionality of Jake Archibald's SVGOMG interface within the code view and allow users to upload SVGs (instead of strictly from web page sourcing).
Open to suggestions as well!
=> Add SVG Gobbler to "Ways to use SVGO"

lib/style.js, lib/style.test.js, plugins/convertPathData.js, plugins/mergePaths.js, plugins/removeHiddenElems.js
computeStyle(node) in isolation is quite slow utility because it
collects style elements across whole document, parses and sort them.
In this diff I splitted it into `collectStylesheet(root)` and
`computeStyle(stylesheet, node)` which are easy integrate with new
visitor plugin api.
cc @XhmikosR
=> Collect stylesheet once per plugin

lib/xast.js, lib/xast.test.js, plugins/mergePaths.js, plugins/mergeStyles.js, plugins/removeComments.js, plugins/removeHiddenElems.js
Wrapping each node with JSAPI class and passing parent to it is not
reliable. Parent may be changed but the reference will stay.
Here I wasn't able to detach comment from parent node for some reason.
Explicit parent node inferred while ast traverse is easier to debug and
work with. Eventually we will not need to wrap each node with JSAPI class.
=> Pass parent node to visitor

lib/svgo/jsAPI.js
Replace deprecated `hasClass` with the new `addClassValueHandler` and deprecated `hasStyle` with `addStyleValueHandler`
=> Replace deprecated methods in jsAPI

plugins/removeUselessStrokeAndFill.js
This is clearer and probably faster too.
=> removeUselessStrokeAndFill.js: use `String.startsWith()`

package-lock.json, package.json, plugins/_applyTransforms.js, plugins/_transforms.js, plugins/cleanupEnableBackground.js, plugins/cleanupListOfValues.js, plugins/cleanupNumericValues.js
* @rollup/plugin-node-resolve  ^11.2.0  →  ^11.2.1
* @types/jest                  ^27.0.0  →  ^27.0.1
* colorette                     ^1.2.2  →   ^1.3.0
* commander                     ^7.1.0  →   ^7.2.0
* css-tree                      ^1.1.2  →   ^1.1.3
* eslint                       ^7.22.0  →  ^7.32.0
* playwright                    ^1.9.2  →  ^1.14.0
* prettier                      ^2.2.1  →   ^2.3.2
* rollup                       ^2.42.1  →  ^2.56.2
* typescript                    ^4.2.3  →   ^4.3.5
=> Update minor and patch dependencies

README.md
Looks like this was missed in #1513.
=> Remove mention of deprecated extendDefaultPlugins.

lib/style.js, plugins/inlineStyles.js
Parsing inline styles with csstree in place is easier.
Caching does not add much value here.
=> Drop node.style usages

README.md
I just spent quite a while trying to upgrade to svgo 2.4 because I was thinking that all the configuration I was passing to `extendDefaultPlugins()` previously should now be in `preset-default` overrides. 
Just adding some examples of enabling other builtin plugins could clarify it? 
Maybe I was just being stupid, but a thought :)
=> Clarify how to enable/configure builtin plugins

lib/svgo/jsAPI.d.ts, plugins/reusePaths.js, test/plugins/reusePaths.02.svg, tsconfig.json
- migrated to visitor plugin api; combination of enter and exit helped
to fit into single traverse
- got rid from the only node.clone() usage in the project so no need to
reimplement it
- the logic is a bit simplified
=> Refactor reusePaths plugin

lib/svgo/plugins.js, plugins/removeUselessStrokeAndFill.js, test/plugins/removeUselessStrokeAndFill.04.svg, test/plugins/removeUselessStrokeAndFill.05.svg, tsconfig.json
The logic is a little messy. Will be better when we drop node 12 support
and use optional chaining.
- get rid from patching params as plugin state
- replaced many node.computedAttr() with style manager
- enabled and fixed removeNone param test (was merged as muted back in 2017)
- added ability to return null and not run visitor in plugins
=> Refactor removeUselessStrokeAndFill

plugins/minifyStyles.js, tsconfig.json
- replaced two traverses with one
Splitted the work to collecting and modifying when root exit.
=> Refactor minifyStyles plugin

plugins/cleanupIDs.js, tsconfig.json
I still did get how id generation works but data flow is clear now at
least.
- got rid of traverse api
=> Refactor cleanupIDs

plugins/removeEditorsNSData.js, tsconfig.json
- got rid from parseName utility in favour of simple string operations
=> Refactor removeEditorsNSData

lib/xast.js, plugins/removeUnusedNS.js, tsconfig.json
- dropped traverse utility which is replaced by visitor
=> Refactor removeUnusedNS plugin

lib/svgo.test.js, lib/svgo/coa.js, lib/svgo/js2svg.js
Addresses #951
Adds the following options to js2svg and CLI:
- eol — can be set to `lf` or `crlf`. If unspecified, js2svg uses the platform EOL.
- finalNewline — defaults to false. If true, js2svg ensures any SVG output has a final newline.
Tests added to cover both options.
=> Allow choosing EOL and appending final newline

.github/workflows/main.yml
Looks like the bug with v8 internals was fixed.
=> Remove node 16 version fix

lib/svgo-node.js, lib/svgo/js2svg.js, rollup.config.js
`os` package in js2svg module bothered me for a long time.
We had to hack rollup to mock it for browser.
Thanks to https://github.com/svg/svgo/pull/1546 we now can pass eol from
svgo-node entry point and simplify build.
cc @adalinesimonian
=> Move platform specific eol to svgo-node entry point

lib/svgo-node.js, lib/svgo-node.test.js
https://github.com/svg/svgo/pull/1565 changed the signature when using SVGO programmatically so that the config argument is required. This breaks Parcel's usage where it might be `undefined` (https://github.com/parcel-bundler/parcel/blob/6f6759e5c2140aa8d7c3be70d56432258439ff19/packages/optimizers/svgo/src/SVGOOptimizer.js#L26-L32).
I've matched the original `optimize` function, and add some basic tests to cover it.
Refs https://github.com/parcel-bundler/parcel/pull/6481#discussion_r707864127
=> Fix config type

plugins/collapseGroups.js, tsconfig.json
- covered with tsdoc
Part of the code is still complicated. Will come to it eventually.
=> Refactor collapseGroups

lib/style.js, lib/style.test.js, lib/svgo/svg2js.d.ts, lib/types.ts, tsconfig.json
node.parentNode will be removed in v3 along with JSAPI class wrapper on
each node.
Style manager uses it to find inherited styles. To workaround this
I collected all parents along with all styles. This constraints style
manager to work only with initial ast which should not be a problem as
each plagin execution is isolated.
Also covered style manager tests with tsdoc.
Better review with hidden whitespaces.
=> Avoid node.parentNode in style manager

bin/svgo, lib/svgo/coa.js, package-lock.json, package.json
Ref https://github.com/ai/nanocolors
Nanocolors is the new player in color libraries. And it's perfectly
packaged as all @ai packages. Colorette is already replaced even
in transitive dependencies.
=> Replace colorette with nanocolors

lib/parser.js, lib/style.test.js, lib/svgo.js, lib/svgo/svg2js.d.ts, lib/types.ts, test/svg2js/_index.test.js, tsconfig.json
Moved to lib/parser.js. The code will be slightly simpler
when JSAPI will be removed in v3.
=> Cover svg parser with tsdoc

plugins/removeAttrs.js, test/plugins/removeAttrs.06.svg
This is a follow-up of #1560 and should fix #1581. The PR attempt to fix an issue when the plugin is called without the `attrs` option. The code expects that the `attrs` option is present and throw an error when it's not because we end up having `attrs = [undefined]` (see below). 
Technically this should be an error but it would be a breaking change. We can start by introducing a warning (what this PR does) and in a future major version throw an error. I added a test where input = output when `attrs` is not provided i.e. noop.
```
TypeError: Cannot read properties of undefined (reading 'includes')
94 |         for (let pattern of attrs) {
95 |           // if no element separators (:), assume it's attribute name, and apply to all elements *regardless of value*
> 96 |           if …
```
=> fix(plugin): removeAttrs: warn without attrs

plugins/mergeStyles.js, test/plugins/mergeStyles.12.svg, tsconfig.json
- covered with tsdoc
- replace another closestByName usage with visitSkip symbol to skip
subtree instead of skipping element by ancestor
- added one more test case
Better review with hidden whitespaces as most code just got bigger indent.
=> Refactor mergeStyles

lib/svgo/coa.js, package-lock.json, package.json, test/cli/cli.test.js
nanocolors checks for --color and --no-color flags to force or disable
output coloring. Which can be used instead of strip-ansi package which
btw introduced vulnerability recently.
=> Replace strip-ansi with --no-color flag

lib/svgo-node.js
Ref https://github.com/svg/svgo/issues/1596
At the moment dynamic import may randomly fail with segfault.
To workaround this for some users .cjs extension is loaded
exclusively with require.
=> Load .cjs with require only

plugins/inlineStyles.js, test/plugins/inlineStyles.14.svg, test/plugins/inlineStyles.16.svg, tsconfig.json
This is a big one
- got rid from another closestByName usage
- delegated removing empty defs elements to removeEmptyContainers plugin
- got rid from all css-tools usages (most inlineStyles code was there
for some reason)
- combined a few loops
- fixed useMqs option (I would remove it in v3 for simplicity as it
seems nobody use it)
cc @strarsis
=> Refactor inlineStyles

lib/xast.js, plugins/removeHiddenElems.js
The last usagee of closestByName utility based on node.parentNode
is removed here. One step closer to clean ast in v3.
=> Replace closestByName utility with visitSkip

plugins/removeDimensions.js
This addresses a very minor typo, but came across this while reading up on the plugin itself.
=> Correct typo in comment in removeDimensions plugin

plugins/applyTransforms.js, plugins/convertPathData.js, test/plugins/convertPathData.11.svg, tsconfig.json
- applyTransforms is prepared to be a separate plugin, in v3 I will
remove it from convertPathData
- migrated to tsdoc
- removed optimisation with stroke-width inside id (still not idea how
it worked)
- added deoptimisation when id is on element to fix redefining in `<use>`
- got rid from latest usage of node.computedAttr and node.parentNode (🎉)
=> Refactor applyTransforms

lib/svgo.test.js, lib/svgo/plugins.js, plugins/preset-default.js
Preset documentation and warning [here](https://github.com/svg/svgo/commit/cb7e9be623b6e2fbbfcb9b67c4c85131e1477925) got me confused. I think these changes should reduce others confusion.
* warn **any** override that is not in the default list
* use actual plugin names in the warning message
For context, I'm migrating from SVGO v1 and I came straight to the config docs here (https://github.com/svg/svgo#configuration) when I realised there were config changes.
I read the `preset-default` docs and saw the `overrides` option, quickly copy pasted my previous config over and changed to the new API:
```js
name: 'preset-default',
params: {
overrides: {
removeXMLNS: true,
removeTitle: true,
removeViewBox: false,
addAttributesToSVGElement: {/* ... */},
},
},
```
And see the new warning:
```
You …
```
=> More helpful preset warnings

lib/css-tools.js, lib/style.js, package.json, plugins/inlineStyles.js, yarn.lock
Currently when installing `svgo` the following warning is displayed:
> npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
This PR removes that warning by removing `stable`. As the `stable` package notice says `Array.sort(..)` guarantees a stable sort for reasonable recent versions of JavaScript already. See [caniuse](https://caniuse.com/mdn-javascript_builtins_array_sort_stable) data to decide whether to accept this PR.
=> Remove `stable` package in favor of native stable sort

plugins/cleanupIds.js, test/plugins/cleanupIds.21.svg
Hello!
The problem is with `<animate>'s` `begin` clearing. For example if both `id="2"` and `<animate begin="2.5s">` are present in svg, it changes to `id="a"` and `<animate begin="a.5s">` which is incorrect value.
This bug was originally found here https://github.com/svg-sprite/svg-sprite/issues/526
=> fix: begin's attribute incorrectly modification

plugins/convertPathData.js
I'm currently profiling my build pipeline and noticed that the `strongRound` function showed up a couple of times, followed immediately with a bit of GC cleanup shortly after. We can speed up that function by avoiding the string casting caused by `Number.prototype.toFixed()`.
In my project's build pipeline with lots of svg icons this saves about 1.4s in total.
=> Speed up strongRound by avoiding string casting

lib/path.js
I'm currently profiling my build setup and noticed that `stringifyNumber` pops up here and there. Instead of going with the double regex replace approach, we'll go with the faster approach in `removeLeadingZero`.
In total the changes in this PR speed up the build by about `0.9s` in my project.
=> Speed up stringifyNumber

README.md
Preview: https://github.com/ADTC/svgo/blob/patch-1/README.md
* Split up code blocks by moving text outside them. (This also ensures that the Copy function makes sense. _See screenshot:_)
* <img width="380" alt="image" src="https://user-images.githubusercontent.com/6047296/211246090-64749e5f-3f1e-413b-be39-a99fa2f1b425.png">
* Remove the redundant list of default plugins and refer to the table instead.
* Sort the table of plugins alphabetically. (It's easier to scan for a plugin.)
* _I suggest maintaining the sort when adding new items._
* Replace the enabled/disabled code in Default column with just Yes or blank.
* Tabulate the "Other ways to use" section and remove redundant "as a/an".
* Correct the word Donators to Donors.
* Add a new section called _Troubleshooting_.
=> Refactor README to be easier to read through

package.json, test/regression-extract.js, yarn.lock
The regression-test GitHub Action was failing for all pull requests due to not handling the gzipped archive properly.
This resolved it by piping the response body to [`zlib#createGunzip`](https://nodejs.org/api/zlib.html#zlibcreategunzipoptions) first. Also updates the relevant dependencies.
* Closes https://github.com/svg/svgo/pull/1759
* I've noticed sometimes when running all tests locally or on CI, it hangs at the end. Will investigate this later. 🤔
=> test: fix regression testing action

test/svgo/_index.test.js, test/svgo/keyframe-selectors.svg
Adds test for issue reported regarding keyframe selectors.
This issue was caused by an upstream bug in [csstree](https://github.com/csstree/csstree/issues/178), which [CSSO](https://github.com/css/csso/commit/d0eecfbd29ca9d9af1681bfe6386489b8de74082) resolved on their end.
I can confirm that with svgo v3.0.2 the issue on longer occurs. However, I think it's worth including a unit test for this before closing the issue.
Uses a simplified version of my original SVG for the test. This is primarily to ensure it does not remove the `to` keyword, which was the original bug.
* For https://github.com/svg/svgo/issues/1631
=> test: add check for keyframe selector to

plugins/reusePaths.js, test/plugins/reusePaths.04.svg, test/plugins/reusePaths.05.svg
If an SVG already had a `defs` tag, the `reusePaths` plugin would create a new one anyway. This changes it so if a `defs` tag is found to exist in the document already, reuse and append to it.
This avoids having 2 `defs` in the same document after optimizing, which is unexpected, and also reducing the SVG size further.
When reusing paths in an existing `defs` tag, it kept around useless nodes that sometimes even broke the SVG. This removes the node if it's an `href` only, and removes it if it's an `id` only pointing to another `href`, and points elements directly to that `href` instead.
The plugin used to output this before, which includes some redundant nodes that broke SVGs:
```xml
<defs>
<use xlink:href="#a"/>
<use id="b" xlink:href="#a"/>
<clipPath id="c">
<use href="#b" width="100%" …
```
=> fix(reusePaths): reuse defs tag if exists and remove redundant nodes

plugins/reusePaths.js, test/plugins/reusePaths.06.svg
Fixes a bug where the `reusePaths` plugin would reuse the node ID that it's optimizing, but that ID was also referenced in a `href` elsewhere in the document, so it unintentionally applied the path to other nodes.
```svg
<svg xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-29.947 60.987 69.975 102.505">
<g transform="translate(-59 64)">
<g id="b">
<path id="a" fill="#000" d="M0 0v1h.5Z" transform="rotate(18 3.157 -.5)"/>
<use xlink:href="#a" width="1" height="1" transform="scale(-1 1)"/>
</g>
<use xlink:href="#b" width="1" height="1" transform="rotate(72)"/>
<use xlink:href="#b" width="1" height="1" transform="rotate(-72)"/>
<use xlink:href="#b" width="1" height="1" transform="rotate(144)"/>
<use xlink:href="#b" width="1" height="1" …
```
=> fix(reusePaths): dont reuse id if referenced in href

plugins/removeRasterImages.js
In practice, this plugin does not work to remove embedded jpg images.
On further inspection, it's because the plugin is looking for `image/jpg`, which I'm not even sure is a valid mimetype. Inkscape uses `image/jpeg` as the mimetype for embedded JPG images.
=> Add support for image/jpeg mimetype

package.json, yarn.lock
Locally and on CI the tests sometimes hang at the end, but I don't see any obvious errors in our test suite. 🤔
Before investigating further, I think it'd be best to just update Jest and see how it goes. So far, I've been unable to reproduce the issue with this.
=> test: update jest

package.json, plugins/cleanupIds.js, test/plugins/cleanupIds.22.svg, yarn.lock
The `cleanupIds` plugin was only checking for the first reference to an ID in any given attribute. If the attribute referenced a second ID, that reference wouldn't be counted.
This resulted in nodes being removed wrongfully because we missed where it was referenced due to backing out early.
* Updates the `regReferencesUrl` regex to be global, and we iterate results instead of take the first only.
* No longer copies the attribute value before iterating, as this can mutate between iterations. 
With only `cleanupIds` enabled.
| [SVG](https://upload.wikimedia.org/wikipedia/commons/1/19/Logo_TVE-1.svg) | time | % reduced | final size | borked |
|---|---|---|---|---|
| Original | | | 7.462 KiB |
| v3.0.2 | 6 ms | 16.4% | 6.239 KiB | borked | 
| main (82593c6134e29a3b6195b48eb3e4d5046de4bee9) | …
=> fix(cleanupIds): handle when 2 ids referenced in one attr

plugins/inlineStyles.js, test/regression.js
To enable another regression test, I've resolved the issue that was causing it to fail.
Style property names are case-insensitive, for example `fill`, `FILL`, and `FiLl` are all valid but refer to the same property. So when inlining styles, we compare the lowercase strings and only use the last instance of the property rather than embed them all.
This also results in smaller files in the case that properties are assigned more than once with different capitalization… though I doubt that really happens in the wild.
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 360">
<style>
#c {fill: red }
#c {FiLl: oRaNgE }
</style>
<circle id="c" fill="blue" cx="140" cy="220" r="50"/>
</svg>
```
Before this would output an inline style like: `style="FiLl:orange;fill:red"`.  
Now instead …
=> fix(inlineStyles): case insensitive style props

yarn.lock
Performs two things:
* Deduplicate dependencies in our `yarn.lock` file with `yarn dedupe`.
* Upgrade dependencies with Dependabot alerts with `yarn up -R {}`.
This only impacted `devDependencies`, and did nothing to our tests or bundle sizes, etc.
=> deps: update deps based on dependabot alerts

plugins/minifyStyles.js, test/plugins/minifyStyles.11.svg
CSSO accepts a `usage` argument, which allows better optimizations since it has the context of the document. This is provided in separate arrays for `tags`, `classes`, `ids`, etc.
Reference: https://github.com/css/csso#usage-data
However, if CSSO has `undefined`/`null` for one of these, it interprets that as unknown/no usage data provided, so it's not safe to remove those things.
For example, if CSSO receives `undefined` for class usage, then it won't remove any classes because it doesn't know whether they're used or not. We have to pass an empty array to tell it no classes have been used in the document.
Reference: https://github.com/css/csso/blob/master/test/usage.js#L81
Also refactors the `minifyStyles` plugin while I was working here, and removes the `style` node entirely if it's …
=> fix(minifyStyles): pass empty arrays for usage

plugins/inlineStyles.js, test/plugins/inlineStyles.21.svg, test/plugins/inlineStyles.22.svg
When running into a multi-class selector with `inlineStyles`, it would only remove the first class of the selector instead of all of them.
This iterates the classes in the selector instead of only taking the first. Also performs some minor refactors.
* Discovered in https://github.com/svg/svgo/issues/1743#issuecomment-1734948374
=> fix(inlineStyles): remove all classes in multiclass selector

lib/svgo-node.test.js, lib/svgo.test.js, plugins/removeDesc.js
As the description of the plugin states, it should only remove the description if we can see it's just editor attribution, since this element is used for accessibility.
This behavior was silently changed in the following commit, with no public discussion:
* https://github.com/svg/svgo/commit/055e303607d53a3d539761d8727d86c03b2e88c1#diff-a49dddaf43efeb074adb9f9911b934cc9b359d34c11303c1210929c90284e44bR8
That commit also makes quite a few other controversial changes, including enabling `removeViewBox` by default, which was explicitly disabled a few years prior because it was causing issues for users.
I elaborate on this here:
* https://github.com/svg/svgo/issues/1786#issuecomment-1732401612
In general, accessibility is more important than optimizations, so while I could update the …
=> fix(removeDesc): removeAny should be disabled by default

lib/svgo/tools.js, plugins/cleanupIds.js, plugins/minifyStyles.js, plugins/removeUselessStrokeAndFill.js
I'd like for SVGO to have more utilities, so we can have more consistent behavior between plugins and simplify the plugins themselves.
One clear pick was determining if a node contained scripts, which was done differently across several plugins. This creates a utility that takes from existing checks, and adds more.
A node that meets one of the following conditions is treated as one that contains scripts:
* If there is a `<script>` tag that contains text.
* If there is a `<a>` tag with a JavaScript URI.
* If there is an event attribute.
* More context on the individual checks in https://github.com/svg/svgo/pull/1807
=> refactor: create hasScripts util

lib/svgo.js
If we received null/undefined/empty plugins, instead of crashing, log a warning and ignore them.
Also updates the error message when a malformed configuration comes in to direct users to the documentation. Later I want to take a page from Vercel's book and made a dedicated page in the docs for various errors, but I will come to this later.
* Closes https://github.com/svg/svgo/issues/1727
=> fix: warn and do not crash on null plugin

yarn.lock
Updates a vulnerable dependency, this only impacts dev/CI!
* Similar to https://github.com/svg/svgo/pull/1799
=> deps: update @babel/traverse

README.md
[image-webpack-loader](https://github.com/tcoopman/image-webpack-loader) is deprecated and replaced with [image-minimizer-webpack-plugin](https://github.com/webpack-contrib/image-minimizer-webpack-plugin/#optimize-with-svgo)
=> README: image-webpack-loader -> image-minimizer-webpack-plugin

plugins/prefixIds.js
In Prefix IDs, we accept a function for the `prefix` parameter. However, the function is called every time an identifier is encountered, so instances of the same identifier are assigned different prefixes, breaking documents.
There are two solutions for this:
1. The plugin interface provides the identifier, which the user can use as a seed to generate a reproducible prefix for a given identifier.
2. We maintain an internal dictionary of prefixes, and refer to the cache when we encounter an identifier again.
I've opted for option 2 for now. Motivation:
* So the plugin works the way it was intended to be used already, without asking users to learn or change their existing configuration.
* Fits the more common use case. Most instances where users want `prefixIds` is to avoid ID collisions …
=> fix(prefixIds): dynamic functions should produce same prefix for given id

plugins/plugins-types.ts, plugins/removeComments.js, test/plugins/removeComments.03.svg
Converts the hard-coded exception to a param so users can override this behavior to preserve custom patterns or drop the logic altogether.
We retain the existing exception as the default value, as this convention is interpreted across minifiers as important. For example, Font Awesome prefixes their comment with a `!`.
```
```
However, we also allow users to pass custom patterns, or either `preservePatterns: []` or `preservePatterns: false` to indiscriminately remove comments.
This is completely backward compatible.
I also replaced the `ignored comment` in the tests with something that matches the kind of comment we're expecting to encounter with this prefix.
* Closes https://github.com/svg/svgo/issues/1811
=> fix(removeComments): make preserving comments a param

plugins/removeScriptElement.js, test/plugins/removeScriptElement.04.svg
When making `removeScriptElement` remove attributes and JavaScript URIs as well, I introduced a bug.
When collapsing, a node's children, there's no need to call `detachNodeFromParent`. This led to dropping more elements we should've.
=> fix(removeScriptElement): collapse a tag propertly

plugins/removeScriptElement.js, test/plugins/removeScriptElement.05.svg
This was hardcoded to use `href` and `xlink:href` before. Now it checks for attributes ending with `:href` in case the xlink namespace is added with a non-standard name.
I was testing in the browser, and it was possible to bypass the plugin before by adding `xlink` with `xmlns:uwu="http://www.w3.org/1999/xlink"`.
=> fix: remove hrefs for unconventional namespaces

lib/style.js, lib/svgo/plugins.js, package.json, plugins/inlineStyles.js, plugins/plugins-types.ts, plugins/removeUnknownsAndDefaults.js, test/plugins/inlineStyles.23.svg, test/regression.js, yarn.lock
When running this plugin on an SVG with an empty block in the CSS, it would apply it to the matched elements by adding an empty `style` attribute. See the test for an example.
This resolves that by just dropping the declaration if it's empty.
I've also done some chores on the side.
* Exposed `compareSpecificity` from `lib/styles.js` and uses that in the Inline Styles plugin.
* Fixed the URL for where `compareSpecificity` was derived from.
* Replace the comment where we import `specificity` with the fact that it is part of the **internal API**, not just that it's not defined in `@types/csso`. As part of the internal API, there is no contract with semver. It can break at any time, even with minor or patch updates, so I've pinned the dependency in `package.json`. 
* Moves docs to the types …
=> fix(inlineStyles): empty css block created empty attribute

lib/style.js
This resolves the error a user of SVGR ran into.
If an SVG features `keyframes` with the `-webkit` prefix, it would throw an error before. This will treat them the same as regular `keyframes`.
You can see a dated article that explains the use of `@-webkit-keyframes` at the following:
https://webkit.org/blog/324/css-animation-2/
As SVGs/styles still use this property in the wild, it makes sense that we at least not crash when it pops up.
* Reported in https://github.com/gregberge/svgr/issues/768
=> fix: skip keyframes with webkit prefix

.github/workflows/main.yml
Now that Node v20 is LTS, we should use Node 20 for CI and run tests on a Node v20 environment as well.
I will not remove any of the others yet, but it's worth noting that the following are no longer supported, including security updates:
* Node v14 since April 2023
* Node v16 since September 2023
=> ci: use and run tests for node 20

docs/03-plugins/inline-styles.mdx, docs/03-plugins/remove-attributes-by-selector.mdx, docs/03-plugins/remove-comments.mdx, docs/03-plugins/remove-empty-text.mdx, docs/03-plugins/remove-hidden-elems.mdx, docs/03-plugins/remove-useless-stroke-and-fill.mdx, lib/style.js, lib/style.test.js, plugins/inlineStyles.js, test/plugins/inlineStyles.24.svg, test/plugins/inlineStyles.25.svg
SVGs can have the same presentation attribute declared redundantly in both the node attributes and `<style>` tag.
This wouldn't break anything, but we can shave off a few more bytes by dropping the attribute in this case. 
We drop the attribute instead of the style because the style has more priority. If we dropped the style, it could be the style of another selector with a lower specificity would be used instead, affecting rendering.
* Refactors parts of the `inlineStyles` plugin.
* Creates the `includesAttrSelector` utility, so we don't remove an attribute if that's used as part of a CSS selector elsewhere.
* Adds a test for `@-webkit-keyframes` which was missed on a previous PR.
* Revise some of the documentation.
=> feat(inlineStyles): remove redundant presentation attrs

docs/03-plugins/convert-one-stop-gradients.mdx, docs/03-plugins/merge-paths.mdx, lib/parser.js, lib/stringifier.js, plugins/_collections.js, plugins/convertOneStopGradients.js, plugins/removeAttributesBySelector.js, plugins/removeDesc.js, plugins/removeTitle.js, plugins/reusePaths.js, test/svgo/_index.test.js, test/svgo/pre-element-pretty.svg, test/svgo/pre-element.svg
While working on the demo for https://github.com/svg/svgo/issues/1794, I noticed an issue with how we handle `pre` tags in a `foreignObject`.
The `pre` tag is space sensitive, so adding or removing whitespace from either end will change the result. This expands the list of elements that we don't trim to include `pre`. I did not do this in `_collections.js` since that was focused on SVG nodes, so I've put it in `tools.js`.
Feedback welcome if you know a better place this constant could live, but I would prefer if we didn't maintain it twice between `parser.js` and `stringifier.js`.
Before it would output one of the following depending on if `js2svg.pretty` was enabled or not.
=> fix: dont trim pre elements

lib/stringifier.js, lib/svgo/tools.js, plugins/applyTransforms.js, plugins/moveGroupAttrsToElems.js
If a node has transforms applied via both the SVG `transform` attribute and the CSS `transform` property in a `<style>` node, then skip it.
The current implementation doesn't handle this correctly and breaks SVGs. Until we have a solution for this, we should drop the logic in this scenario.
* Fixed a typo in a comment, `graniends` → `gradients`
* Created a `includesUrlReference` utility that we can use across plugins.
* Makes `moveGroupAttrsToElems` and `applyTransforms` use `includesUrlReference` which is more robust.
* Problem found in https://github.com/gregberge/svgr/issues/768
=> fix(convertPathData): skip if transform overridden in styles

plugins/inlineStyles.js, test/plugins/inlineStyles.03.svg, test/plugins/inlineStyles.05.svg, test/plugins/inlineStyles.16.svg, test/plugins/inlineStyles.19.svg, test/plugins/inlineStyles.22.svg
When inlining styles, they should prioritized in two ways:
* Highest specificity should be inlined.
* Inlined properties should be in the order they appeared in the stylesheet.
The part we were missing is that if multiple selectors have the same specificity, then we should make sure the inlined styles include the properties in the order they appear from top to bottom.
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 268.65 348.6">
<style>
.a, .b {
animation: a 1s ease-in-out;
}
.a {
animation-delay: 1s
}
@keyframes a {
50%{transform:scaleY(.9)scaleY(.9)}
100%{transform:scaleY(1)}
}
</style>
<g class="a">
<path d="M72.22,317c-11.54-42.95-1.64-69.06,30.26-79.83L106,236l1,3.56a144.53,144.53,0,0,0,14.74,35.15l.88,1.49-.64,1.6a234.19,234.19,0,0,0-11.12,38.62l-.58,2.75-37.32.46Z" …
```
=> fix(inlineStyles): inline styles in order of priority

lib/style.js, package.json, plugins/inlineStyles.js, test/plugins/inlineStyles.26.svg, yarn.lock
Inline Styles would remove the class from a node after inlining the styles. However, this would break vectors if that class was still needed by another vector though traversal.
For example:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45 35">
<style>
.a {}
.c {}
.a .b {
fill: none;
stroke: #000;
}
</style>
<g class="a c">
<circle class="b" cx="42.97" cy="24.92" r="1.14"/>
<path class="b" d="M26,31s11.91-1.31,15.86-5.64"/>
</g>
</svg>
```
We can inline `.a`, however, by removing the `class="a"` on the group, `.a .b` no longer selects the `circle` and `path` nodes.
This preserves that class if it's traversed in another selector. The class `c` is still removed.
* Despite adding a dependency on `css-what`, it's worth noting we already depend on it, as it's a dependency of …
=> fix(inlineStyles): dont remove wrapper class if traversed

README.md, SECURITY.md
Revamps the README to tidy things up, reference the new documentation, and drop some unmaintained or deprecated ways to use SVGO.
I changed the `alt` attribute of the hero image because it wasn't fulfilling it's purpose. The `alt` attribute is what should be used instead if the user is unable to see the image for whatever reason. However, this image is purely decorative and so can be skipped over in the scenario it doesn't load.
See: https://www.w3.org/WAI/tutorials/images/decision-tree/
Adds a badge guiding users to the SVGO documentation. I also modified the alt to match the text we'd expect to see if the badge loaded.
* Proofread the README, revising grammar and making some subjective changes.
* SVG is an acronym, so all uppercase. (`svg` → `SVG`)
* Reduce verbosity in general, …
=> chore: revamp readme

README.md, plugins/inlineStyles.js
This PR is similar to https://github.com/svg/svgo/pull/1832, but for IDs rather than classes. We shouldn't remove the ID of the node if the ID is traversed in another CSS selector.
Includes minor rewording to the README, this is an extension to https://github.com/svg/svgo/pull/1835.
* Closes https://github.com/svg/svgo/issues/952
=> fix(inlineStyles): dont remove id if traversed in another selector

CONTRIBUTING.md, docs/03-plugins/convert-colors.mdx, docs/03-plugins/remove-xlink.mdx, docs/03-plugins/remove-xmlns.mdx, lib/builtin.js, package.json, plugins/plugins-types.ts, plugins/removeEditorsNSData.js, plugins/removeXMLNS.js, plugins/removeXlink.js, test/plugins/removeXlink.01.svg, test/plugins/removeXlink.02.svg, test/plugins/removeXlink.03.svg, test/plugins/removeXlink.04.svg
Ref https://github.com/svg/svgo/pull/1508
The new plugin removes xmlns:xlink from <svg> and replaces xlink:href
with href attribute.
xlink namespace is obsolete in SVG 2. Href attribute is recommended
replacement to xlink:href.
This plugin will be enabled by default in SVGO 3.
See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
cc @devongovett
=> [new plugin] remove-xlink-ns

docs/03-plugins/remove-xlink.mdx
Minor change to show the params heading in the new Remove XLink plugin. I forgot to add it when introducing the param in the Remove XLink plugin.
The way we do it now is a bit messy and error-prone, so I'll look more into if we can safely detect and add the header while automatically updating the ToC.
=> docs: add params section to remove xlink docs

docs/03-plugins/remove-xlink.mdx, docs/03-plugins/reuse-paths.mdx
Another minor PR to update the documentation for Remove XLink and and Reuse Paths.
* In Remove XLink, recommend that it's added toward the end of the pipeline so it can convert `xlink:href`s that are added by other plugins.
* In Reuse Paths, recommend that if SVG 1.1 compatibility isn't a requirement, users can run Remove XLink to reduce more bytes.
=> docs(removeXlink): add tip to run plugin last

lib/svgo-node.test.js
'should respect line-ending config' failed because parameters were out of order on expected result. CRLF version of the tests was out of sync with LF version.
Fixes #1849
=> test failed on Windows

.github/workflows/main.yml
We had an issue where platform-specific tests weren't kept up-to-date since they don't all run in CI, and active maintainers only use Linux/macOS.
This adds windows-latest in the test runners.
Running tests 8 times seems a bit much (build minutes + carbon footprint) but I'm also reluctant to drop Node v14 support until SVGO v4 is released. I'm thinking for now we go with this, but if we run into any problems, I can drop Node v14 support in a minor update instead. (i.e. SVGO v3.1.0)
Both Node v14 and Node v16 are no longer supported, so I think it's sensible to drop them soon. I'd like to take this one at a time though, so starting with Node v14. Node v16 only came out of its support window recently anyway.
* Found in https://github.com/svg/svgo/pull/1850 and …
=> ci: run tests on windows

lib/svgo.d.ts
Improve loadConfig types, fixed like:
```ts
await loadConfig(null, 'webpack context');
await loadConfig(undefined, 'webpack context');
```
=> feat: Improve loadConfig types

lib/svgo/coa.js
Actually the number is always green.
I change the color to red when the filesize is increased.
=> change profit color output to green and red

plugins/convertPathData.js, test/plugins/convertPathData.29.svg
I think the issue there is caused by the path joining acting weird because `prev` is set to a nonexistent (filtered out) command. This PR moves where `prev` is set to fix.
Fix #1855
=> fix(convertPathData): handle setting prev properly to fix path joining and #1855

plugins/removeEmptyContainers.js, test/plugins/removeEmptyContainers.06.svg
=> Don't remove an empty container if parent is "switch"

plugins/cleanupIds.js, test/plugins/cleanupIds.24.svg
=> fix(cleanupIds): properly handle begin regex to fix #1775

docs/03-plugins/cleanup-enable-background.mdx, plugins/cleanupEnableBackground.js, test/plugins/cleanupEnableBackground.05.svg
* Before `cleanupEnableBackground` only worked on attributes, now it will work on inline-styles too.
* When the inline-style includes an enable-background declaration multiple times, only the last one is preserved.
* When the inline-style is found to be empty, or becomes empty during this optimization, the attribute is dropped entirely.
With only `preset-default` enabled.
| [SVG](https://github.com/svg/svgo/issues/1740#issue-1550057265) | time | % reduced | final size | borked |
|---|---|---|---|---|
| Original | | | 0.149 KiB |
| v3.0.5 | 13 ms | 0.7% | 0.148 KiB | | 
| main (39e855be9e0170aeaef9a4a4edadc675db68640b) | 15 ms | 0.7% | 0.148 KiB | | 
| this branch | 12 ms | 28.1% | 0.107 KiB |
* Closes https://github.com/svg/svgo/issues/1740
=> fix(cleanupEnableBackground): clean up inline styles too

plugins/removeHiddenElems.js, test/plugins/removeHiddenElems.14.svg, test/plugins/removeHiddenElems.15.svg
Relocate logic to run in node.exit instead of checking in svg's exit:
- remove broken uses
Changed from checking each use to making a list of uses, to fix #1851
- remove unused defs
Fixed a typo so it actually removes them, and add some safeguards
- remove empty defs
Changed from checking each def to making a list of defs
=> fix(removeHiddenElems): handle defs better

plugins/prefixIds.js, test/plugins/prefixIds.12.svg
This fixes a bug in the prefixIds plugin.  It assumed that the `<style />` element will have a single text fragment underneath.
So this works:
```
<style>
.class1 {}
...
.classN {}
</style>
```
The above parses so that node.children[0] is a "text" node with all the CSS classes where "node" is the style element.
And this fails:
```
<style>
.class1 {}
.class2 {}
</style>
```
This fails because only node.children[0] is processed and node.children looks something like:
[
.class1 (type = "text")
comment (type = "comment")
.class2 (type = "text")
]
=> Include all configuration in the <style /> element

plugins/cleanupIds.js, test/plugins/cleanupIds.25.svg
References to IDs in `href` or `url()` references are URIs, and so should be URI encoded/decoded.
We'll have to review and update all usage in SVGO for this, but for now, I've resolved the immediate issue found in Cleanup IDs.
* Fixes https://github.com/svg/svgo/issues/1696
=> fix(cleanupIds): handle uri encoded references

lib/svgo/tools.js, plugins/cleanupIds.js, plugins/prefixIds.js, plugins/removeHiddenElems.js
In multiple areas in the code, we were handling URL references in attributes poorly. Namely, when checking for them, we should check for `url(#a)`, `url('#a')`, and `url("#a")`, but in some places we were only checking the first.
This also migrates some logic from `cleanupIds` to a new utility to centralize collecting references from an attribute, which is already being used by another plugin.
* Closes https://github.com/svg/svgo/issues/1711
=> fix: improve handling of url references in reference attributes

package.json, plugins/_path.js, plugins/_transforms.js, plugins/convertStyleToAttrs.js
- Include *.mjs and *.cjs files in the eslint configuration. These files exist in the test suite.
- Remove eslint-disable comments that aren't silencing a error.
=> Tidy up eslint config and usage

.github/dependabot.yml
I went with monthly so that it's not too noisy, but should still help keeping up actions up to date.
=> chore: Add dependabot config for action updates

test/regression.js
Goes from 76 seconds to 61 seconds in my tests.
Two main changes:
- instead of chunking the array, use workers that subtract as needed
Bonus: this means that they go in alphabetical order
- serve SVGs, optimized or not, on demand instead of warming them up
This means no optimizing skipped tests
Admittedly won't be as useful once the PR that moves skipping tests into the extractor gets merged, but hey, it'll still decrease initial startup time
*I was going to make it even faster with `node-canvas`, but the w3 tests are a bit eccentric and fail to render properly there, and I don't know of any other convenient rendering libs
=> chore: speedier regression testing

lib/path.js, lib/svgo/tools.js
Refactors `#stringifyPathData` and the functions it calls, which now runs notably faster.
The scenarios I measured in microbenchmarks ran in half the time.
* When stringifying, return both the numeric and string representation so we can perform checks with math instead of string parsing.
* When stringifying path data, use a single loop instead of creating an intermediate array and looping through that after.
Time to run the full SVGO Test Suite proposed in https://github.com/SethFalco/svgo/pull/1.
| Environment | Time |
|---|---|
| GitHub Actions | 20.5 minutes |
| My personal laptop (4 cores, 8 threads) | 15.0 minutes |
=> refactor: improve performance of stringifyPathData

plugins/mergePaths.js
Merges part of https://github.com/svg/svgo/pull/1764.
* Rather than use `detachNodeFromParent` per child, collect the children and remove them all at once after we've finished iterating.
* Don't needlessly run `path2js` if `attributesAreEqual` was `false` anyway. Before we'd assign this boolean, run `path2js`, and then throw it away if it was `false`. ^-^'
In the specific SVG I was testing against, this improves speeds by 6-8%. However, this has a negligible impact on our overall regression test times.
Reference: https://commons.wikimedia.org/wiki/File:Saariston_Rengastie_route_labels.svg
* Some code authored by [mozzie](https://github.com/mozzie) in https://github.com/svg/svgo/pull/1764
=> refactor(mergePaths): improve performance

package.json, plugins/convertPathData.js, plugins/mergePaths.js, yarn.lock
Removed unneeded calls from mergePaths plugin.
1) Instead of calling detachNodeFromParent, nodes are tagged and removed after each node has been looped through. 
2) Eliminated unneeded js2path and path2js conversion by keeping the current path in memory for the duration of the loop.
=> Improve mergePaths performance on large files

lib/style.js, lib/types.d.ts, package.json, plugins/inlineStyles.js, yarn.lock
Follow upstream commit:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/394c175b3bee0890febfb41b2321b1e11e8b1bdd
Can remove the ts-ignore when importing specificity.
The specificity function return a 3-tuple, so update the type alias in lib/types.d.ts.
=> chore: Update @types/csso and correct types

package.json, plugins/prefixIds.js, yarn.lock
Updates `css-tree` and `@types/css-tree`, and removes redundant `ts-ignore` comments now that we have more up-to-date types.
=> deps: update css-tree and clean ts-ignores

plugins/convertPathData.js, test/plugins/convertPathData.34.svg
`t` works by reflecting points. This PR simply keeps track of the previous point, so `q` can be converted to `t` when the control point reflects properly.
closes #1888
this doesn't affect the test cases much but applies to some certain icons (found in places like material-symbols), where circles are approximated using `t`
the previous logic was also incorrect (it would convert some stuff wrongly)
=> feat(convertPathData): allow converting q to t in more cases

plugins/convertPathData.js
While reviewing https://github.com/svg/svgo/pull/1889 I'd made some changes locally which I just wanted to push.
This has no (or negligible) impact on performance, it's just to keep things cleaner.
* Make JSDocs with a single line, a single line.
* Declare variables individually in some places.
* Define type `any` on `prev`. We were literally disabling type checking with magic comments on _every usage_ anyway.
* Use `string.includes` instead of `~string.indexOf` as there is no significant difference while the former is more semantic.
* Stop using `apply` methods, we can just use the spread operator.
* Use `Math.sqrt` instead of `Math.hypot` as `Math.hypot` has overhead from improved precision, which we don't need here.
* Replace the regex decimal number check with a math implementation. …
=> refactor(convertPaths): clean up plugin

lib/svgo-node.test.js, lib/svgo.test.js, test/coa/_index.test.js
Avoid unnecessary assertions such as `expect(true).toBe(false)`. Instead, assert the exception using the `toThrow()` matcher. Where that is insufficient, use `expect.assertions()`. Unwrap exceptions in promises using `expect.rejects`.
These patterns are documented at:
- https://jestjs.io/docs/expect#tothrowerror
- https://jestjs.io/docs/tutorial-async#rejects
- https://jestjs.io/docs/expect#expectassertionsnumber
=> chore: Use idiomatic Jest patterns to assert exceptions

lib/path.test.js, lib/style.test.js, lib/svgo-node.test.js, lib/svgo.test.js, lib/xast.test.js, test/cli/cli.test.js, test/plugins/_index.test.js, test/plugins/prefixIds.test.js, test/svg2js/_index.test.js, test/svgo/_index.test.js
Avoid type coercion for assertions by using toBe, toBeNull, and toStrictEqual.
These matchers are documented at:
- https://jestjs.io/docs/expect#tobevalue
- https://jestjs.io/docs/expect#tostrictequalvalue
- https://jestjs.io/docs/expect#tobenull
=> chore: Improve Jest tests with more precise assertions

lib/path.js, lib/svgo/tools.js, plugins/_transforms.js, plugins/convertPathData.js, plugins/convertTransform.js, test/plugins/_transforms.test.js, test/plugins/convertTransform.05.svg
I have divided this pull request into two commits, if you want to review it, please look at one commit at a time:
1. Functional changes relevant to the bug being fixed
2. Various refactors
When we encounter a transform matrix with both shears (`a B C d e f`) set or unset, we conditionally invert `sx` and `sy`. This is needed most of the time to preserve the original sign (`+/-`) of scales (`A b c D e f`) since this gets lost after squaring in `Math.hypot`.
The previous implementation lead us to make conversions like the following, which are both wrong:
| Matrix | Expected | Actual | Notes |
|---|---|---|---|
| `matrix(0 -1 -1 0 0 0)` | `scale(1 -1)rotate(90)` | `rotate(-90)`
| `matrix(0 1 1 0 0 0)` | `matrix(0 1 1 0 0 0)` | `rotate(90)` | The decomposed matrix is `scale(1 -1)rotate(-90)`, …
=> fix(convertTransform): fix scale and rotate on skew + refactors

plugins/removeUselessDefs.js, test/plugins/removeUselessDefs.04.svg, test/plugins/removeUselessDefs.05.svg
This change applies the same logic used to process `<def>` elements to all non-rendering elements (i.e. preserve referenced children, and only delete the parent if no children remain).
This fix is part of the solution to removing the media-flash.svg mismatches in test-regression. This fix alone does not change the number of regression mismatches.
Closes #1922.
=> Fixed bug in removeUselessDefs

plugins/convertPathData.js, test/plugins/convertPathData.36.svg.txt
fix #1926 by only resetting the control point if an item is included
realistically this should be fine as it'll still get reset on move commands, and likely if a command is dropped the control point stayed the same
there's another issue with how in the case `M0 0Q10 0 10 10Q10 10 10 10T20 20`, convertPathData should convert `T` to longhand and update the control point before dropping the useless command (changing the control point), but that's out of scope for this PR. (if my thinking is correct, i can't think of any cases where converting from q to t is affected by this behavior)
=> fix(convertPathData): fix q control point behavior when item is removed

plugins/removeHiddenElems.js, test/plugins/removeHiddenElems.16.svg, test/plugins/removeHiddenElems.17.svg, test/plugins/removeHiddenElems.18.svg
This change removes non-rendering nodes only if they have no referenced children.
This fix is part of the solution to removing the media-flash.svg mismatches in test-regression. On its own, this fix resolves 8 mismatches in test-regression. In conjunction with PR #1923 this fix resolves 14 mismatches in test-regression.
**Further Discussion**
This plugin has some code that seems like it needs to be removed, but maybe I'm missing something. In addition to the usual return of the visitor functions, this plugin has an explicit call to visit(), with different code than what is in the return value. That causes the tree to be traversed twice, and the `<symbol>` element was being removed in both sets of code. I removed the code in the explicit call to visit(), but there is still code in the …
=> Fixed bug in removeHiddenElems

plugins/collapseGroups.js, test/plugins/collapseGroups.17.svg.txt
In the test case file, before this change, the transform attribute on the group was moved to the child, but the style containing the filter was not moved. This was changing the rendering.
regression.js before fix:
- Mismatched: 214
- Passed: 5308
- Total reduction 764239791 bytes
After fix:
- Mismatched: 201
- Passed: 5321
- Total reduction 764238752 bytes
This removes 13 regression mismatches. Compression of regression files is reduced by 1039 bytes.
Closes #1928
=> fix: collapseGroups does not move attributes atomically

docs/03-plugins/remove-deprecated-attrs.mdx, lib/builtin.js, plugins/_collections.js, plugins/plugins-types.d.ts, plugins/preset-default.js, plugins/removeDeprecatedAttrs.js, test/plugins/_collections.test.js, test/plugins/removeDeprecatedAttrs.01.svg.txt, test/plugins/removeDeprecatedAttrs.02.svg.txt, test/plugins/removeDeprecatedAttrs.03.svg.txt, test/plugins/removeDeprecatedAttrs.04.svg.txt, test/plugins/removeDeprecatedAttrs.05.svg.txt, test/plugins/removeDeprecatedAttrs.06.svg.txt, test/plugins/removeDeprecatedAttrs.07.svg.txt, test/plugins/removeDeprecatedAttrs.08.svg.txt
The new removeDeprecatedAttributes removes deprecated attributes from
the SVG document. For example, the "version" attribute on the "svg"
element is deprecated and not recommended as documented on MDN:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/version
> Deprecated: This feature is no longer recommended. Though some
> browsers might still support it, it may have already been removed from
> the relevant web standards, may be in the process of being dropped, or
> may only be kept for compatibility purposes. Avoid using it, and
> update existing code if possible; see the compatibility table at the
> bottom of this page to guide your decision. Be aware that this feature
> may cease to work at any time.
The document:
```
<svg version="1.1" viewBox="0 0 100 100" …
```
=> feat(removeDeprecatedAttrs): new removeDeprecatedAttrs plugin

lib/svgo.d.ts, lib/types.d.ts
Follow up to another PR where the contributor is no longer responsive, but suggestions were made.
This improves the types for custom plugins to better suit the actual structures in SVGO.
* Closes https://github.com/svg/svgo/pull/1738 (supersedes)
=> chore: improve types for custom plugin

plugins/removeHiddenElems.js, test/plugins/removeHiddenElems.19.svg.txt
removeHiddenElems was removing all `<path>` elements with opacity:0. If the path was referenced by a `<textPath>`, this caused the text to disappear.
This resolves 10 regression errors:
```
svgs/oxygen-icons-5.113.0/scalable/apps/digikam.svg     pass
svgs/oxygen-icons-5.113.0/scalable/apps/showfoto.svg    pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/16x16/digikam.svg pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/16x16/showfoto.svg        pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/22x22/digikam.svg pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/22x22/showfoto.svg        pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/32x32/digikam.svg pass
svgs/oxygen-icons-5.113.0/scalable/apps/small/32x32/showfoto.svg        pass …
```
=> fix: removeHiddenElems - treat <path> with opacity:0 as non-rendering node.

lib/svgo.test.js, plugins/_transforms.js, plugins/convertTransform.js, test/plugins/_index.test.js, test/plugins/_transforms.test.js, test/plugins/convertTransform.01.svg.txt, test/plugins/convertTransform.02.svg.txt, test/plugins/convertTransform.03.svg.txt, test/plugins/convertTransform.05.svg.txt, test/plugins/convertTransform.06.svg.txt, test/plugins/convertTransform.07.svg.txt, test/plugins/convertTransform.10.svg.txt, test/plugins/convertTransform.11.svg.txt, test/plugins/convertTransform.12.svg.txt, test/plugins/convertTransform.13.svg.txt, test/plugins/convertTransform.14.svg.txt
Closes #1268 
The matrixToTransform() function in \_transforms.js was causing mismatches in some of the regression tests. I tracked this down to some conditions where the code was trying to move the scale() transform to a different place. I tried fixing the original code, but the scale adjustments were woven all through the function, so I ended up rewriting it.
The new version fixes 23 regression errors compared to the original version, and reduces the compressed file size of the regression files by an additional 153,223 bytes over the original version.
Changes to the code:
- The new code closely follows the algorithm referenced in the original code at
https://frederic-wang.fr/decomposition-of-2d-transform-matrices.html.
- The algorithm referenced above always decomposes a matrix in the …
=> fix: matrixToTransform()

lib/svgo/coa.js
Previously, SVGO would crash if the output location had a trailing slash and the location didn't exist.
This should be behaving the same as when the directory did exist, and putting the optimized file with the same name inside that directory.
This fixes that behavior, so we'll treat this as if the user wants to create that directory and output the optimized SVG to a file with the same name in that directory.
See my comment in #1675 for more context:
* https://github.com/svg/svgo/pull/1675#discussion_r1459295954
* Closes https://github.com/svg/svgo/pull/1675
=> fix: output to new directory if trailing slash

docs/03-plugins/merge-paths.mdx, plugins/mergePaths.js
Right now all plugins use a default floatPrecision except for mergePaths. This means that if another plugin doesn't round the paths internally, the whole precision leaks out.
We fix this by setting it to 3 by default. This closes #1944, and also probably helps with size reduction.
TODO: figure out a test case (feel free to suggest one)
=> fix(mergePaths): use a default floatPrecision

lib/style.js, plugins/collapseGroups.js, test/plugins/collapseGroups.18.svg.txt
collapseGroups was not detecting a filter when it was in a style rather than an attribute.
This change resolves one regression mismatch (svgs/oxygen-icons-5.113.0/scalable/mimetypes/small/64x64/image-x-adobe-dng.svg) and reduces pixel mismatches by 67.
This type of problem seems like it is probably widespread (including in the same conditional in this plugin, where it is looking for a clip-path). I didn't see any tools to query the style attribute in a standard way. The solution in this PR is not going to scale well - it seems like it would be desirable to have a standardized, efficient way to query/change the style attribute - maybe it's there and I'm missing it?
=> Check for filter in style as well as attribute.

lib/parser.test.js, plugins/_collections.js, plugins/removeScriptElement.js, test/plugins/removeEmptyContainers.06.svg.txt, test/plugins/removeScriptElement.03.svg.txt, test/plugins/removeXlink.03.svg.txt
`<a>` elements should be parsed the same as `<tspan>`, etc. This change adds `<a>` to the textContent collection. It also adds a test file for the parser, updates the expected results for several test cases, and changes the removeScriptElement plugin to remove empty text nodes contained by removed `<a>` elements.
To see the problem visually, optimize the following file with default SVGO settings and view both input and output files:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
<text x="10" y="20">this is a test</text>
<text x="10" y="35" xml:space="preserve">
<a href="https://svgwg.org/svg2-draft/linking.html#Links">
this is a test   
</a>
</text>
</svg>
```
Before the fix, the second line is shifted from the correct position after being optimized.
=> fix: <a> element not parsed as text

README.md
When running svgo with a custom config named svgo.config.js on node 20.11.0. It fails to load the config file with the following error:
```
./svgo.config.js:1
export default {
^^^^^^
SyntaxError: Unexpected token 'export'
at internalCompileFunction (node:internal/vm:77:18)
at wrapSafe (node:internal/modules/cjs/loader:1288:20)
at Module._compile (node:internal/modules/cjs/loader:1340:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Module._load (node:internal/modules/cjs/loader:1023:12)
at cjsLoader (node:internal/modules/esm/translators:356:17)
at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
at async …
```
=> chore: Update the README docs to suggest svgo.config.mjs

lib/path.js, lib/path.test.js
stringifyPathData was not adding a space before numbers which used scientific notation.
This fix does not change the results of regression tests using the current value of floatPrecision: 4 (125 failures, 3794 pixel differences), but when run at floatPrecision:7, failures are reduced from 164 to 93, and pixel mismatches reduced from 32,058 to 3,233.
=> fix: stringifyPathData needs space before scientific notation.

plugins/mergePaths.js, test/plugins/mergePaths.08.svg.txt, test/plugins/mergePaths.09.svg.txt, test/plugins/mergePaths.10.svg.txt, test/plugins/mergePaths.11.svg.txt, test/plugins/mergePaths.12.svg.txt
This PR fixes the problem raised in issue #1267. The general issue is that merging paths into a single element changes the bounding box, so any style that depends on the bounding box of the element may change behavior. This PR disables merging for any paths that have:
- A fill, filter, or stroke that references a URL.
- A clip-path or mask.
It's possible that there are other scenarios where merging should be disabled, but those above are the only ones that I was able to construct a test case for so far.
With the current regression settings, there is no change in pixel mismatches in the regressions. With the Oxygen files, only one file seems to be affected - scalable/status/weather-few-clouds-night.svg. The clouds were rendered incorrectly in the optimized version before the fix.
Closes …
=> fix: mergePaths should not merge paths with styles that depend on bounding box

plugins/addClassesToSVGElement.js, plugins/plugins-types.d.ts, test/plugins/addClassesToSVGElement.test.js
Updates the interface for `addClassesToSVGElement` to match `prefixIds`, where we'll accept `Array<string|function>` instead of just a string.
This way, users can use the node/info property to dynamically set classes across many SVGs.
* Closes https://github.com/svg/svgo/issues/1756
* Closes https://github.com/svg/svgo/pull/1757 (Supersedes)
=> feat(addClassesToSVGElement): allow function as param

plugins/applyTransforms.js, plugins/convertPathData.js, test/plugins/convertPathData.37.svg.txt
If we get a markers only path, for example:
```xml
<path marker-start="url(#a)" marker-end="url(#b)" d="M5 5h0"/>
```
(The path only serves to draw the referenced markers.)
We ensure it always has an extra vertex if it had multiple vertices before optimization. If it did not have multiple vertices, for example it was `M`/`m` commands only, then it has the same behavior as before.
See my comment on the related issue for more info:
* https://github.com/svg/svgo/issues/1493#issuecomment-1974136452
In short, clients consistently render the marker only when a command other than `M` or `m` are used in the path data. If this is removed, in some clients the markers are no longer rendered.
It's unclear from the spec what the intended behavior is, but across all clients, rendering is impacted when …
=> fix(convertPathData): preserve vertex for markers only path

lib/svgo/coa.js
Looking at the source code:
https://github.com/svg/svgo/blob/2442f742398f6c40bcf83b5c34e4a71a023adae1/lib/svgo-node.js#L39-L50
it looks to me like not only .js, but also .mjs, and .cjs extensions are allowed in config files. This PR aligns the help text with the actual behavior.
=> fix(makeProgram): specify .mjs and .cjs config files are allowed

plugins/cleanupIds.js, test/plugins/cleanupIds.26.svg.txt
=> fix(cleanupIds): handle no-uri-encoded references

lib/svgo-node.d.ts, lib/svgo.d.ts, package.json, rollup.config.js, test/svgo.cjs
esm
```ts
import { loadConfig, optimize } from 'svgo';
```
cjs
```ts
const { loadConfig, optimize } = require('svgo');
```
browser
```ts
import { optimize } from 'svgo/browser';
```
=> Fixed V3.3.0 Common JS missing loadConfig and optimize exports

package.json, yarn.lock
Without this tests fail on Windows cmd (CI works because by default it's using bash)
Requires #1986 and #1987.
=> chore: add cross-env and rimraf so that tests work everywhere

docs/03-plugins/addAttributesToSVGElement.mdx, docs/03-plugins/addClassesToSVGElement.mdx, docs/03-plugins/cleanupIds.mdx, docs/03-plugins/cleanupListOfValues.mdx, docs/03-plugins/cleanupNumericValues.mdx, docs/03-plugins/convertColors.mdx, docs/03-plugins/convertPathData.mdx, docs/03-plugins/convertShapeToPath.mdx, docs/03-plugins/convertStyleToAttrs.mdx, docs/03-plugins/convertTransform.mdx, docs/03-plugins/inlineStyles.mdx, docs/03-plugins/mergePaths.mdx, docs/03-plugins/minifyStyles.mdx, docs/03-plugins/prefixIds.mdx, docs/03-plugins/removeAttributesBySelector.mdx, docs/03-plugins/removeAttrs.mdx, docs/03-plugins/removeComments.mdx, docs/03-plugins/removeDesc.mdx, docs/03-plugins/removeElementsByAttr.mdx, docs/03-plugins/removeEmptyText.mdx, docs/03-plugins/removeHiddenElems.mdx, docs/03-plugins/removeUnknownsAndDefaults.mdx, docs/03-plugins/removeUselessStrokeAndFill.mdx, docs/03-plugins/removeXlink.mdx, docs/03-plugins/sortAttrs.mdx
To make maintenance of the documentation more user-friendly, we're adapting the front matter to Markdown at build time in the svgo.dev repository.
This converts all the plugin descriptions, which previously used HTML, to use Markdown instead.
=> chore: use markdown in frontmatter

docs/03-plugins/prefixIds.mdx, docs/03-plugins/removeViewBox.mdx
Introduces a new section to the prefixIds documentation to highlight the value of reproducible IDs. That's not to say other solutions are bad, but just that where viable, a reproducible prefix ID may be preferred, especially if working with React.
=> docs: add section on reproducible ids for prefix ids

docs/03-plugins/cleanupListOfValues.mdx, docs/03-plugins/removeEmptyContainers.mdx, docs/03-plugins/removeXMLNS.mdx
Just a few more chores while going through the documentation.
* cleanupListOfValues was missed when we removed inline titles from each documentation page. This removes the heading.
* For removeEmptyContainers, mention that the `<svg>` is ignored sooner, and correct the wording.
* In removeXMLNS, be explicit instead of using "this", and use consistent plugin names, i.e. `removeXlink`, not `Remove XLink`.
=> docs: minor restructure and rewording

docs/02-preset-default.mdx
`preset-default` was transposed to `default-preset` in the docs. This PR fixes it.
=> [docs] fix transposition of preset-default

.github/workflows/main.yml, test/regression-extract.js, test/regression.js
Expands the regression test task to include KDE's Oxygen Icons.
SVGO is in dire need of better quality assurance, and Oxygen Icons is a good library to use as it has relatively complex SVGs compared to other icon libraries.
This PR is to track progress. We need to fix cases that are broken in Oxygen Icons, and optimize SVGO, tests, and the pipeline so that we can complete the regression tests quicker. Since we started planning this, we've already taken the time down from 23.4 minutes.
Any help to fix tests reported in this PR or improve performance would be very welcome. Performance is particularly valuable right now, as it makes iterating on fixes faster. (Success criteria for performance improvements is that the number of mismatches didn't increase.)
This also updates the regression …
=> test: expand and optimize regression testing

package.json, test/regression-extract.js, yarn.lock
Native fetch is present on Node.js >= 18. In #2002 we drop support for Node.js 14, but since this code is only used in tests I guess we could live with it.
=> chore(tests): Switch to native fetch

plugins/convertColors.js, test/plugins/convertColors.01.svg.txt
Commaless `rgb(0 0 0)` is now allowed by browsers, and using commas is considered [legacy](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#legacy_syntax_comma-separated_values). This allows the convertColors plugin to parse and convert these colors, even making SVGs more compatible.
=> fix(convertColors): accept commaless rgb

.github/workflows/main.yml, eslint.config.mjs, lib/svgo-node.js, lib/svgo.d.ts, lib/svgo.js, lib/version.js, package.json, scripts/sync-version.js, test/browser.js, test/svgo.cjs, test/svgo/_index.test.js
Adds a `VERSION` export, similar to React, Axios, and Lodash.
This will enable third-party libraries to check what version of SVGO is in use during runtime, and is intended to supersede the need to import our `package.json` file, which we don't want to make part of our public API.
Updates our ESLint config from `2021` to `'latest'`. I wanted to keep it at 2022 or later as we can use top-level awaits.
```js
import { VERSION } from 'svgo';
console.log(VERSION);
// 4.0.0
```
```js
const svgo = require('svgo');
console.log(svgo.VERSION);
// 4.0.0
```
* From discussion in https://github.com/svg/svgo/pull/1999#issuecomment-2102802055
=> feat: export version constant

.yarn/patches/sax-npm-1.4.1-503b1923cb.patch, lib/parser.js, package.json, yarn.lock
Migrates from our [~~maintained~~ unmaintained fork of sax-js](https://github.com/svg/sax) to [upstream](https://github.com/isaacs/sax-js).
While sax-js is not actively maintained, it has received some updates which has allowed it to catch up with our fork, and has more bug fixes in it. I've also made contributions to sax-js myself to get here.
* https://github.com/isaacs/sax-js/pull/266
* https://github.com/isaacs/sax-js/pull/267
* https://github.com/isaacs/sax-js/pull/268
* https://github.com/isaacs/sax-js/pull/272
There is one change we needed that was not merged upstream, but instead we apply a patch via Yarn in this repository. This is acceptable in this case as the change only impacts the browser bundle, which is our job to generate, and contains the change to `lib/sax.js` in the …
=> chore: migrate to upstream sax

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, docs/01-index.mdx
Trivial PR that amends version strings in the documentation.
* In the bug report template, to use more recent versions as placeholders.
* In CONTRIBUTING.md, it has the wrong version before. Node v20 is needed to contribute.
* In docs/01-index.mdx, to reflect that we dropped support for v14 in https://github.com/svg/svgo/pull/2002
=> chores: amend version strings

lib/svgo/coa.js, package.json, yarn.lock
Commander v11 requires Node.js 16 so this should probably be merged after #2002 and the other PRs.
Please note that this bumps many major versions. I checked commander's release notes, but this could definitely use some more eyes for any breaking changes that might affect svgo.
Ping me when needed for a rebase.
=> chore!: Update commander to v11

lib/svgo-node.d.ts, lib/svgo-node.js, lib/svgo.d.ts, lib/svgo.js, lib/svgo/plugins.js, plugins/plugins-types.d.ts, test/browser.js, test/svgo.cjs, test/svgo/_index.test.js
Exposes a new property called `builtinPlugins`. This is intended to cover use cases where clients imported/required the list of available plugins or the default preset.
If you import/require the array of built-in plugins, or a single plugin during runtime, this is now a top-level exported member instead:
```diff
// builtin.mjs - get an array of all built-in plugins
- import { builtin } from 'svgo/lib/builtin';
+ import { builtinPlugins } from 'svgo'
// plugin.mjs - get a single plugin
- import presetDefault from 'svgo/plugins/preset-default';
+ import { builtinPlugins } from 'svgo';
+ const prefixDefault = builtinPlugins.find(plugin => plugin.name === 'preset-default');
// plugin-map.mjs - get all plugins as a map using the plugin name as a key
import { builtinPlugins } from 'svgo';
const …
```
=> feat: expose builtin plugins

lib/svgo-node.d.ts
Re export `Config` definition for node module.
=> fix: fixed Config definition for node

lib/builtin.js, lib/svgo.d.ts, lib/svgo/coa.js, lib/svgo/plugins.js
Call `Object.freeze` on `builtinPlugins` and the `plugins` property of presets, so the arrays/pipelines can not be modified from outside the package.
=> chore: freeze plugin arrays

.github/workflows/main.yml
The matrix is getting a little big but better test everything. We could probably just test Node.js 16 on Ubuntu to save some time, or exclude some things. Let me know if you have any suggestions.
=> chore(ci): add Node.js 22

lib/svgo.js, lib/version.js, package.json
Adds an alias to convert `removeScriptElement` to `removeScripts`.
This makes it, so this is less likely to be a breaking change for downstream projects.
The changes to our default plugins are less of an issue because redundant `overrides` don't throw errors, and most downstream projects disabled `removeTitle` and `removeViewBox` already anyway, so that change isn't going to be breaking for them at all.
However, the rename of `removeScriptElement` would produce a fatal crash if an end-user had that in their config for a downstream project. So instead, let's alias it so projects like SVGR, ipx, Docusaurus etc, can upgrade to SVGO v4 without having to increment their major version.
=> fix: add alias of removeScriptElement to removeScripts

lib/svgo.d.ts, lib/svgo/plugins.js
While consuming the types downstream, it was unhelpful to have `unknown` instead of a more concrete type like `string`. That was a mistake on my part when initially writing it.
I used `unknown` because we don't know what plugin it is, but we do certainly know it has to be a `string` and `object` in any case, so that's more appropriate.
=> chore: use concrete types for generics

docs/03-plugins/cleanupNumericValues.mdx, plugins/cleanupNumericValues.js, test/plugins/cleanupNumericValues.03.svg.txt
Updates the documentation to clarify explicitly that the plugin impacts whitespace. Internally, it's because we parse all numbers in the attribute into an array, then rewrite it back.
I also fix a bug that I discovered while testing the issue reported. When an attribute like `"  0   0  150 100  "` comes up, SVGO inserts a `0` to the start and end of the attribute, completely changing the meaning.
This was because when we do the split, the array we get back starts with an empty string and ends with an empty string, which were then converted to `0`, resulting in `"0 0 0 150 100 0"` instead of `"0 0 150 100"`.
```js
seth@seth-pc-tux:~$ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> Number("")
0
```
Now we filter them out before parsing.
Just applying a recommendation …
=> fix: don't insert 0 at start or end of attribute if whitespace

lib/style.js, lib/style.test.js
Following SVG fails cause of `-o-keyframes` and `-moz-keyframes`. It did work in svgo 2.8
```
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="-256 -256 512 512">
<title>Snow CSS3 animation example</title>
<desc>Example of SVG animation using CSS3 and SMIL with a Merry Christmas &amp; Happy New Year ambigram and lighting filters, drawn by CMG Lee.</desc>
<style type="text/css">
@keyframes x {
from {
transform: translate(100px, 0);
}
to {
transform: translate(-99px, 0);
}
}
@keyframes y {
from {
transform: translate(0,-500px) rotate( 0deg);
}
to {
transform: translate(0, 500px) rotate(90deg);
}
}
@-moz-keyframes x {
from {
-moz-transform: translate(100px, 0);
}
to { …
```
=> Support -o-keyframes and -moz-keyframes

package.json
This makes it easy to see the HTML report with all the info
=> chore: enable more coverage reporters

docs/03-plugins/addAttributesToSVGElement.mdx, plugins/addAttributesToSVGElement.js
Trivial PR that fixes a typo in addAttributesToSVGElement, and removes some redundant words from the JS Doc of the plugin.
=> chore(addAttributesToSVGElement): fix typoes in docs

lib/path.js
While looking through `path.js`, I noticed we had a `isWsp` function, which wasn't immediately obvious was an abbreviation for `isWhiteSpace`. So I renamed it to `isWhiteSpace` so it's obvious what it's doing.
From there, since we're stepping through a string char by char before calling the function, it's redundant to call `codePointAt` when we can just compare the string immediately. This is both faster and more readable for maintainers.
Finally, I just apply a proposal from SonarLint to replace an `else { if () }` with `else if ()`.
```js
const Benchmark = require('benchmark');
const suite = new Benchmark.Suite;
const data = [
'0', // false
'1', // false
'-', // false
'.', // false
' ', // true
'\t', // true
'\n', // true
'\r', // true
' ', // false (technically true, but we didn't …
```
=> refactor: dont covert to charcode in iswhitespace

plugins/removeScripts.js
CodeQL picked up a redundant regular expression we had in removeScripts. This just removes it since it functionally changes nothing.
=> chore(removeScripts): remove redundant regex pattern

plugins/cleanupNumericValues.js
1. Uses trim on the string instead of iterating the results after splitting.
2. Reduces duplicate matching in the regex pattern. 
The performance difference is minor, but measurable:
```js
const data = [
'0 0 120 120',
'0 0 230 120',
'110 0 120 120',
'0 0 200.28423 200.28423',
'20.000001 -19.99999 17.123456 70.708090',
' 0 0      150 100 ',
'  0  0  0.5  .5  ',
];
function splitAndFilter(viewbox) {
return viewbox
.split(/(?:\s,?|,)\s*/g)
.filter(v => v.length != 0)
.map(Number);
};
// split and filter x 566,854 ops/sec ±0.58% (95 runs sampled)
function trimAndSplit(viewbox) {
return viewbox
.trim()
.split(/(?:\s,?|,)\s*/g)
.map(Number);
};
// trim and split x 583,812 ops/sec ±0.56% (96 runs sampled)
```
* Alternate solution for https://github.com/svg/svgo/pull/2036
* Based on conversation …
=> refactor(cleanupNumbericValues): improve how viewbox is split

eslint.config.mjs, lib/svgo-node.js, lib/svgo.d.ts, lib/svgo.js, lib/xast.js, plugins/_collections.js, test/browser.js, test/svgo.cjs
For SVGO v4, we're changed how we handle exports.
> We use the `exports` field in `package.json` to define the public interface of the package. This enforces boundaries between the intended public API and any internal structures/helpers that we use internally.
> 
> — https://github.com/svg/svgo/releases/tag/v4.0.0-rc.0
I had omitted most of the exports before, as they were mostly intended for SVGO itself to consume. However, consumers of the library are using these functions while maintaining their custom plugins, so we're changing how they're exported, but the functions will otherwise still be available in v4.
```diff
- import { querySelector, querySelectorAll } from 'svgo/lib/xast.js';
+ import { querySelector, querySelectorAll } from 'svgo';
- import _collections from …
```
=> add: centralize exports to svgo

.prettierignore, .yarnrc.yml, eslint.config.mjs
Sets the `npmRegistryServer` in our `.yarnrc.yml` so that the `yarn npm login` and `yarn npm publish` command hit the correct server.
Also adds `.yarnrc.yml` to our linter ignore configs as I'm treating this as a generated file.
=> chore: add npm registry server to yarnrc

package.json, yarn.lock
Bump dependencies, no break change.
```json
"css-tree": "^2.3.1 --> ^3.0.1"
"picocolors": "^1.0.0 --> ^1.1.1"
```
=> feat: Bump deps

plugins/removeEmptyContainers.js, test/browser.js, test/plugins/removeEmptyContainers.07.svg.txt, test/regression.js, yarn.lock
Fixes a bug where we were too eager to remove empty containers.
We already had logic to skip removing empty containers if it had the `filter` attribute, which is needed to apply a filter to the whole area. However, the `filter` can also be defined through CSS. We did not properly handle this case, and treated the node as if it had no `filter` at all.
This computes the styles and checks the stylesheet as well. (We also move the logic down to avoid computing the styles eagerly.)
=> fix(removeEmptyContainers): skip if filter is applied via styles as well

plugins/_transforms.js
Fixed link in doc comments. Previous link reaches a 404.
Old:
https://frederic-wang.fr/decomposition-of-2d-transform-matrices.html
New:
https://frederic-wang.fr/2013/12/01/decomposition-of-2d-transform-matrices/
=> Update links in _transforms.js

.github/workflows/spellcheck.yml, cspell.jsonc, docs/04-plugins/cleanupIds.mdx, docs/04-plugins/convertPathData.mdx, lib/parser.js, lib/svgo.d.ts, lib/svgo.test.js, lib/svgo/tools.js, plugins/_collections.js, plugins/_path.js, plugins/cleanupAttrs.js, plugins/convertPathData.js, plugins/convertStyleToAttrs.js, plugins/inlineStyles.js, plugins/minifyStyles.js, plugins/plugins-types.d.ts, plugins/removeOffCanvasPaths.js, plugins/removeUselessStrokeAndFill.js, plugins/removeXlink.js
Add spellchecking to CI. This is mostly for documentation, but we may enforce it on most if not all files anyway.
Rational is that we've let typos onto the site on too many occasions, which just isn't a great look imo, so this will hopefully reduce that.
While this PR is in a draft state, it is configured to check all files. However, before merging we will enable `incremental_files_only` so that it only checks modified/added files.
* In `_collections`, replaced `indetermined` with [`indeterminate`](https://developer.mozilla.org/docs/Web/CSS/:indeterminate). There is no `indetermined` pseudo-class. This was a typo of indeterminate, which is a pseudo-class.
* Replace some instances of British English with American English.
Would've prevented all of the following:
* …
=> ci: add spellcheck

lib/xast.js, plugins/_path.js, plugins/addAttributesToSVGElement.js, plugins/cleanupEnableBackground.js, plugins/convertPathData.js, plugins/inlineStyles.js
Minor change to use the `@ts-expect-error` directive instead of `@ts-ignore`. In the near future, we should work towards removing all of these directives by having better typing.
=> chore: migrate from ts-ignore to ts-expect-error

lib/parser.js, lib/stringifier.js, lib/svgo-node.d.ts, lib/svgo-node.js, lib/svgo-node.test.js, lib/svgo.d.ts, lib/svgo.js, lib/svgo.test.js, lib/svgo/coa.js, lib/svgo/css-select-adapter.js, lib/svgo/plugins.js, package.json, plugins/cleanupListOfValues.js, plugins/cleanupNumericValues.js, plugins/inlineStyles.js, tsconfig.json, yarn.lock
This is part 1 of what will be a series of pull requests to improve our typechecking with tsc.
This is proving important as some users have reported issues with type declarations. Before I tackle the issue directly, I want to improve our TypeScript setup. This will help in improving our QA for SVGO too, which is a long-term project I'd been focused on since joining as a maintainer.
**Note: This is not an effort to migrate the project to TypeScript, and I do not have plans to migrate the project to TypeScript. This is to improve the JSDoc types and our usage of tsc.**
This does leave a few instances of `{any}` in, which I'll resolve in future. My goal is better, not perfect, and I'll iterate on this in other PRs.
Upgrades the version of typescript used in the project as there was a bug …
=> fix: improve jsdoc types and remove excludes

package.json, yarn.lock
Our workspaces fetched 3 different versions of `glob` before. By upgrading `@rollup/plugin-commonjs` from v25 to v26, this avoided an extra package since the upstream project upgrades to glob v10 which already pulled in by other dependencies.
Upgrades `rollup` version.
=> deps: upgrade rollup and @rollup/plugin-commonjs

lib/style.js, lib/svgo.d.ts, lib/svgo/css-select-adapter.d.ts, lib/svgo/css-select-adapter.js, lib/xast.js
Significantly improves type checking for `lib/svgo/css-select-adapter.js`. Before, we declared an explicit `any` over the options.
* No longer declares the type of `querySelector` and `querySelectorAll` in our `.d.ts` file. Instead, we use a JSDoc type, and export that in our `.d.ts`. This achieves the same result, but we maintain the type with the implementation, leaving less risk for it to fall out of sync.
* Deletes `lib/svgo/css-select-adapter.d.ts` and uses the upstream types when we define our config. (I did declare `any` for two functions as they were annoying to resolve, I will look at this in future. Again, I'm striving for better, not perfect.)
=> chore: stronger typing for xast/css-select code

lib/path.js, lib/stringifier.js
A small chore that refactors `lib/stringifier.js`.
* Utilizes early returns instead of `else` branches.
* Replaces the `if`/`else` chain with a `switch`.
* Moves the shared part of `#stringifyAttributes` outside the conditionals.
* Sorts `@typedef` directives.
---
Context: A lot of my PRs at the moment are just to clean up code, as I'm spending a lot of time going through our APIs and types. My focus right now is on quality of code, documentation, types, and testing, etc, rather than on bug fixes. Should be releasing v4.0.0-rc.2 this weekend. :crossed_fingers:
=> chore: refactor stringifier.js

docs/02-usage/02-browser.mdx, docs/06-migrations/01-migration-from-v3-to-v4.mdx
Very minor change to remove the `slug` from front matter where it's the same as what the generated slug would be anyway. (From the file name.)
=> chore: omit unneccesary slugs in docs

lib/svgo-node.js
`configFile` is optional in 4.0.0-rc.1
https://github.com/svg/svgo/blob/49954bc0d9ec3dcf166bef59657ad1e78909ff1e/lib/svgo-node.d.ts#L10-L17
=> fix: fix `loadConfig` types

plugins/_collections.js
Adds Krita's SVG extension namespace to the list of editor namespaces.
I did export an SVG from Krita manually to confirm this is an expected namespace that Krita actually exports SVGs with.
* Fixes https://github.com/svg/svgo/issues/2130
* Originally reported in https://github.com/gregberge/svgr/issues/1001#issue-3049625403
=> chore: add krita namespace to list of editor namespaces

plugins/_collections.js
I've added [Boxy SVG](https://boxy-svg.com/)'s namespace to the set of editor namespaces according to https://svgo.dev/docs/plugins/removeEditorsNSData/. Boxy SVG markup looks like this:
```svg
<svg ... xmlns:bx="https://boxy-svg.com">
...
</svg>
```
=> feat: add editor namespace for Boxy SVG

docs/04-plugins/convertColors.mdx, docs/04-plugins/removeAttrs.mdx, plugins/convertColors.js, test/plugins/convertColors.04.svg.txt, test/plugins/convertColors.06.svg.txt
Fixes an issue where we convert `currentColor` to lowercase, so it becomes `currentcolor` (not spec compliant) and breaks in specific SVG previewers.
The impact was low as many clients supported both `currentColor` and `currentcolor`, however, what we had before was incorrect.
* Fixes https://github.com/svg/svgo/issues/2136
* Introduced in https://github.com/svg/svgo/pull/1692
=> fix(convertColors): use currentColor instead of currentcolor

lib/svgo-node.js
Fixes the issue with the module loader for configuration files on win32 platforms by converting the given path to a file:// type url.
This is a regression that was introduced by https://github.com/svg/svgo/pull/2107 where the import call was adapted to use path.resolve instead primarily for type checking purposes.
To restore the original behaviour but also keep the types intact we simply roll back to the url.pathToFileURL call and afterwards convert the URL object to string. It seems weird but does what it should. 
* Fixes https://github.com/svg/svgo/pull/2140
=> fix(#2140): SVGO fails with ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows

plugins/removeUnknownsAndDefaults.js, test/plugins/removeUnknownsAndDefaults.17.svg.txt
The removeUnknownsAndDefaults plugin was removing attributes that were used in CSS selectors, which is problematic because that breaks styles!
We should be checking if that attribute is used as part of an attribute selector before we commit to removing it.
I've implemented it to only check for the existence of an attribute selector that references the key, rather than actually compare the value, because attribute selectors are complicated. For example:
* `[preserveAspectRatio]`
* `[preserveAspectRatio=]`
* `[preserveAspectRatio^="x"]`
* etc…
In future, we can explore making a more robust utility. But for now, let's at least not break SVGs.
* Fixes https://mastodon.social/@sir_pepe/114319751487861964
* _(Yes I know, a bit weird that I'm referring to a Mastodon post rather than a GitHub …
=> fix(removeUnknownsAndDefaults): skip if attr used in css selector

docs/06-migrations/01-migration-from-v3-to-v4.mdx
Fixes two minor typos in the migration guide.
Spellcheck can't save me if the spelling was correct, I just used the wrong word. ^-^'
=> docs: fix typos in migration guide

docs/02-usage/index.mdx, docs/04-plugins/inlineStyles.mdx, docs/04-plugins/removeUnknownsAndDefaults.mdx
A problem we have on the SVGO.dev website is that we don't use right keywords to really match what a user might be searching for.
We have a plugin called `inlineStyles`. A user will find it when they search `inline styles`, yet it does not appear when one searches `inline css`. This is very problematic because a user really could search either.
It's not a perfect solution, but to appease both our on-site search engine and global search engines, I want to revise our copy to be clearer and use more keywords that get the page picked up for searches a user that wanted it would realistically do.
For example, for `inlineStyles`, we can refer to it as CSS declarations too. Then both our internal search and any global search engines can more easily make the link to CSS.
* `inlineStyles` - Refer …
=> docs: minor revisions in wording
